#config_version=6

mode:
  start_events:
  - logicblock_grand_prix_counter_complete
  stop_events:
  - multiball_grand_prix_ended
  restart_on_next_ball: false
  priority: 200

multiballs:
  grand_prix:
    ball_count: 1
    ball_count_type: add
    shoot_again: 15s
    start_events: mode_grand_prix_started
    # TODO: entering all 3 "holes" adds a ball
    add_a_ball_events:
    - player_grand_prix_hole_counter_count{current_player.grand_prix_hole_counter_count == 3}

# TODO: counter for each hole
