#config_version=6

multiballs:
  grand_prix:
    ball_count: 3
    ball_count_type: total
    shoot_again: 20s
    enable_events:
    - mode_grand_prix_starting
    start_events:
    - mode_grand_prix_started
    stop_events:
    - mode_grand_prix_stopping
