#config_version=6

ball_saves:
  ball_start:
    active_time: 10s
    # NOTE: hurry_up_time is INCLUDED in active_time
    hurry_up_time: 5s
    auto_launch: true
    grace_period: 2s
    only_last_ball: true # won't save if 2+ balls on playfield
    enable_events:
    - mode_pit_started
    timer_start_events:
    - sw_playfield_active
