#config_version=6

event_player:
  # To activate "green_flag" mode, the user's vehicle
  # must be ready to race:
  s_fuel_active:
  - green_flag{current_player.level_oil == 2 and current_player.level_tires == 2}
  s_oil_active:
  - green_flag{current_player.level_fuel == 2 and current_player.level_tires == 2}
  s_tires_active:
  - green_flag{current_player.level_fuel == 2 and current_player.level_oil == 2}
  # Multiball Started
  mode_grooveline_started:
  - multiball_started
  mode_luxury_started:
  - multiball_started
  mode_grand_prix_started:
  - multiball_started
  mode_red_line_started:
  - multiball_started
  # Multiball Stopped
  mode_grooveline_stopped:
  - multiball_stopped
  mode_luxury_stopped:
  - multiball_stopped
  mode_grand_prix_stopped:
  - multiball_stopped
  mode_red_line_stopped:
  - multiball_stopped
