#config_version=6

config:
- ball_saves.yaml
- event_player.yaml
- mode.yaml
- sequences.yaml
- slide_player.yaml
- sound_player.yaml
- timers.yaml
- variable_player.yaml
- show_player.yaml
- ball_holds.yaml
- shots.yaml
