#config_version=6

segment_display_player:
  ball_started{game.num_players > 0}:
    segment1: "{players[0].score:d}"
    segment2: ""
    segment3: ""
    segment4: ""
  ball_started{game.num_players > 1}:
    segment2: "{players[1].score:d}"
  ball_started{game.num_players > 2}:
    segment3: "{players[2].score:d}"
  ball_started{game.num_players > 3}:
    segment4: "{players[3].score:d}"
  player_score{game.num_players > 0}:
    segment1: "{players[0].score:d}"
  player_score{game.num_players > 1}:
    segment2: "{players[1].score:d}"
  player_score{game.num_players > 2}:
    segment3: "{players[2].score:d}"
  player_score{game.num_players > 3}:
    segment4: "{players[3].score:d}"
