#config_version=6

show_player:
  modes_active_modes_changed:
    flash_color: stop
  mode_pit_started:
    flash_color:
      speed: 8
      show_tokens:
        led: tag_lights_pit_arrow
        color: yellow
  # TODO: Will not re-enable because pit doesn't end,
  # but putting in backfire->started also didn't work
  # even with priority set, not sure why
  mode_pit_started{current_player.level_fuel < 2}:
    flash_color:
      speed: 8
      show_tokens:
        led: l_shoot_fuel
        color: white
  mode_green_flag_stopped:
    flash_color:
      speed: 8
      show_tokens:
        led: tag_lights_pit_arrow
        color: yellow
  mode_green_flag_started:
    flash_color: stop
  timer_skill_shot_started:
    swerve: play
  timer_skill_shot_complete:
    swerve: stop
