#config_version=6

sound_player:
  # initially, player needs to top up
  # fuel to hit green flag
  mode_pit_started:
    pit_ambience:
      action: play
      loops: -1
  mode_backfire_stopped:
    pit_ambience:
      action: play
      loops: -1
  # Reminders to get into the backfire hole
  # and "too late" if not done in time
  timer_backfire_qualification_tick{ticks == 10 and not mode.backfire.active and not mode.green_flag.active}: backfire_reminder
  timer_backfire_qualification_tick{ticks == 1 and not mode.backfire.active and not mode.green_flag.active}: late
  mode_green_flag_stopped:
    pit_ambience:
      action: play
      loops: -1
  s_shooter_lane_inactive{current_player.score == 0}:
    fuel:
      action: play
  s_shooter_lane_inactive{current_player.score > 0}:
    start:
      action: play
  pit_required_fuel:
    fuel:
      action: play
  pit_required_tires:
    tires:
      action: play
  pit_required_lube:
    pit:
      action: play
  green_flag_degrade_all{current_player.level_tires == 1 or current_player.level_lube == 1 or current_player.level_fuel == 1}:
    pit:
      action: play
  # TODO: would like to do this... why no work?
  # s_pit_fuel_active{current_player.level_fuel < 2}: pit_fuel
  # s_pit_lube_active{current_player.level_lube < 2}: pit_lube
  # s_pit_tires_active{current_player.level_tires < 2}: pit_tires
  s_pit_fuel_active: pit_fuel
  s_pit_lube_active: pit_lube
  s_pit_tires_active: pit_tires
  # fallback sound
  sw_tag_bell: bell
