#config_version=6

sound_player:
  # initially, player needs to top up
  # fuel to hit green flag
  s_launch_inactive{current_player.score == 0}:
    fuel:
      action: play
  s_launch_inactive{current_player.score > 0}:
    start:
      action: play
  pit_required_fuel:
    fuel:
      action: play
  pit_required_tires:
    tires:
      action: play
  pit_required_lube:
    pit:
      action: play
  green_flag_degrade_all{current_player.level_tires == 1 or current_player.level_lube == 1 or current_player.level_fuel == 1}:
    pit:
      action: play
  # TODO: would like to do this... why no work?
  # s_pit_fuel_active{current_player.level_fuel < 2}: pit_fuel
  # s_pit_lube_active{current_player.level_lube < 2}: pit_lube
  # s_pit_tires_active{current_player.level_tires < 2}: pit_tires
  s_pit_fuel_active: pit_fuel
  s_pit_lube_active: pit_lube
  s_pit_tires_active: pit_tires
