#config_version=6

variable_player:
  ###########
  # Scoring #
  ###########

  # Most switches aren't worth much since
  # the drivers first goal is to get out
  # of the pit as fast as possible
  sw_pops:
    score: 1
  s_grooveline_active:
    score: 1
  # so skill shot isn't 1000 + 1
  s_backfire_hole_active{not device.timers.skill_shot.running}:
    score: 1
  s_prix_hole_active:
    score: 1
  s_grand_hole_active:
    score: 1
  s_spinner_active:
    score: 1
  s_save_target_active:
    score: 1
  s_bonus_target_active:
    score: 1
  s_swerve1_active:
    score: 1
  s_swerve2_active:
    score: 1
  s_slingshot1_active:
    score: 1
  s_slingshot2_active:
    score: 1
  s_inlane1_active:
    score: 1
  s_inlane2_active:
    score: 1
  s_outlane1_active:
    score: 1
  s_outlane2_active:
    score: 1

  # Skillshots immediately restore fuel resources
  skill_backfire_hit:
    score: 1000
    level_fuel:
      int: 2
      action: set
    level_lube:
      int: 2
      action: set
    level_tires:
      int: 2
      action: set

  #####################
  ## Limited scoring ##
  #####################
  s_pit_fuel_active:
    score: 100
    level_fuel:
      int: 2
      action: set
  s_pit_lube_active:
    score: 100
    level_lube:
      int: 2
      action: set
  s_pit_tires_active:
    score: 100
    level_tires:
      int: 2
      action: set

  mode_green_flag_stopped:
    multiplier:
      action: set
      float: 1
  logicblock_seq_lap_complete:
    lap_count: 1

  # For indicating multiball is ready
  # by lighting the multiball lamp
  # (see modes/pit/code/pit.py)
  logicblock_grooveline_counter_complete:
    is_multiball_ready: 1
  logicblock_luxury_counter_complete:
    is_multiball_ready: 1
  multiball_lock_prix_hole_locked_ball:
    is_multiball_ready: 1
  logicblock_red_line_counter_complete:
    is_multiball_ready: 1
  multiball_stopped:
    is_multiball_ready:
      action: set
      int: 0

  ##########################
  ## Wizard-mode Progress ##
  ##########################
  multiball_grooveline_ended:
    is_grooveline_completed: 1
    game_progress: 1
  multiball_luxury_ended:
    is_luxury_completed: 1
  multiball_grand_prix_ended:
    is_grand_prix_completed: 1
  multiball_red_line_ended:
    is_red_line_completed: 1

  #####################
  ## Per-ball resets ##
  #####################
  ball_will_end:
    grooveline_counter_count:
      action: set
      int: 0
