#config_version=6

variable_player:
  ###########
  # Scoring #
  ###########

  # consider removing points
  # s_disqualifier_active:
  s_pop1_active:
    score: 10
  s_pop2_active:
    score: 10
  s_grooveline_active:
    score: 50
  s_fuel_active:
    score: 100
    bonus: 10
    level_fuel:
      int: 2
      action: set
  s_oil_active:
    score: 100
    bonus: 10
    level_oil:
      int: 2
      action: set
  s_tires_active:
    score: 100
    bonus: 10
    level_tires:
      int: 2
      action: set
  s_backfire_hole_active:
    score: 500
    bonus: 50
  s_prix_hole_active:
    score: 100
    bonus: 10
  s_grand_hole_active:
    score: 100
    bonus: 10
  s_spinner_active:
    score: 10
    bonus: 1
  s_save_target_active:
    score: 10
    bonus: 10
  s_bonus_target_active:
    score: 10
    bonus: 10
  s_swerve1_active:
    score: 10
    bonus: 10
  s_swerve2_active:
    score: 10
    bonus: 10
  s_slingshot1_active:
    score: 10
  s_slingshot2_active:
    score: 10
  s_inlane1_active:
    score: 25
  s_inlane2_active:
    score: 25
  s_outlane1_active:
    score: 50
  s_outlane2_active:
    score: 50

  logicblock_seq_lap_complete:
    lap_count: 1

  # For indicating multiball is ready
  # by lighting the multiball lamp
  # (see modes/pit/code/pit.py)
  logicblock_grooveline_counter_complete:
    is_multiball_ready: 1
  logicblock_luxury_counter_complete:
    is_multiball_ready: 1
  multiball_lock_prix_hole_locked_ball:
    is_multiball_ready: 1
  logicblock_red_line_counter_complete:
    is_multiball_ready: 1
  multiball_stopped:
    is_multiball_ready:
      action: set
      int: 0

  ##########################
  ## Wizard-mode Progress ##
  ##########################
  multiball_grooveline_ended:
    is_grooveline_completed: 1
  multiball_luxury_ended:
    is_luxury_completed: 1
  multiball_grand_prix_ended:
    is_grand_prix_completed: 1
  multiball_red_line_ended:
    is_red_line_completed: 1

  #####################
  ## Per-ball resets ##
  #####################
  ball_will_end:
    grooveline_counter_count:
      action: set
      int: 0
