#config_version=6

# GREEN FLAG
#
# The primary mode of the game when the driver is "ready to
# race". Most other modes will be stacked on top of this mode.
#
config:
- counters.yaml
- event_player.yaml
- light_player.yaml
- mode.yaml
- random_event_player.yaml
- sequence_shots.yaml
- sequences.yaml
- show_player.yaml
- slide_player.yaml
- sound_player.yaml
- variable_player.yaml
