#config_version=6

light_player:
  mode_green_flag_started:
    x_loop_gate:
      color: white
  ######################
  ## Grooveline State ##
  ######################
  player_grooveline_counter_count{current_player.grooveline_counter_count == 1}:
    tag_lights_grooveline: off
    l_grooveline_01: on
  player_grooveline_counter_count{current_player.grooveline_counter_count == 2}:
    tag_lights_grooveline: off
    l_grooveline_01: on
    l_grooveline_02: on
  player_grooveline_counter_count{current_player.grooveline_counter_count == 3}:
    tag_lights_grooveline: off
    l_grooveline_01: on
    l_grooveline_02: on
    l_grooveline_03: on
  player_grooveline_counter_count{current_player.grooveline_counter_count == 4}:
    tag_lights_grooveline: off
    l_grooveline_01: on
    l_grooveline_02: on
    l_grooveline_03: on
    l_grooveline_04: on
  player_grooveline_counter_count{current_player.grooveline_counter_count == 5}:
    tag_lights_grooveline: off
    l_grooveline_01: on
    l_grooveline_02: on
    l_grooveline_03: on
    l_grooveline_04: on
    l_grooveline_05: on
  player_grooveline_counter_count{current_player.grooveline_counter_count == 6}:
    tag_lights_grooveline: on
    l_grooveline_07: off
    l_grooveline_08: off
    l_grooveline_09: off
    l_grooveline_10: off
  player_grooveline_counter_count{current_player.grooveline_counter_count == 7}:
    tag_lights_grooveline: on
    l_grooveline_08: off
    l_grooveline_09: off
    l_grooveline_10: off
  player_grooveline_counter_count{current_player.grooveline_counter_count == 8}:
    tag_lights_grooveline: on
    l_grooveline_09: off
    l_grooveline_10: off
  player_grooveline_counter_count{current_player.grooveline_counter_count == 9}:
    tag_lights_grooveline: on
    l_grooveline_10: off
  player_grooveline_counter_count{current_player.grooveline_counter_count == 10}:
    tag_lights_grooveline: off
