#config_version=6

mode:
  start_events:
  - green_flag
  # shortcuts to resume/start green flag
  - logicblock_backfire_counter_complete
  - skill_backfire_hit
  stop_events:
  - pit_required_lube
  - pit_required_fuel
  - pit_required_tires
  - green_flag_bad_luck
  - green_flag_degrade_all{current_player.level_tires == 1 or current_player.level_lube == 1 or current_player.level_fuel == 1}
  events_when_stopped:
  - start_backfire_qualification
  restart_on_next_ball: true
  priority: 2000
