#config_version=6

show_player:
  # global multiball indicator
  timer_eternal_tick{current_player.is_multiball_ready == 1}:
    lights_blink:
      show_tokens:
        lights: l_multiball
  multiball_stopped:
    lights_blink:
      action: stop
      show_tokens:
        lights: l_multiball
  multiball_started:
    grooveline_soon:
      action: stop
  player_grooveline_counter_count{current_player.grooveline_counter_count == 10}: grooveline_soon
  mode_green_flag_started:
    under_green:
      loops: 0
      sync_ms: 2000
