#config_version=6

show_player:
  player_grooveline_counter_count{current_player.grooveline_counter_count == 10}: grooveline_soon
  mode_green_flag_started:
    signal:
      loops: 0
      sync_ms: 2000
  logicblock_luxury_counter_complete:
    lights_blink:
      show_tokens:
        lights: l_multiball
  multiball_luxury_ended:
    lights_blink:
      action: stop
      show_tokens:
        lights: l_multiball
