#config_version=6

show_player:
  # global multiball indicator
  timer_eternal_tick{current_player.is_multiball_ready == 1}:
    lights_blink:
      show_tokens:
        lights: l_multiball
  sw_tag_rev:
    lights_blink:
      speed: 1.5
      loops: 0
      show_tokens:
        lights: l_tach
  multiball_stopped:
    lights_blink:
      action: stop
      show_tokens:
        lights: l_multiball
  multiball_started:
    token_color_run:
      action: stop
  player_grooveline_counter_count{current_player.grooveline_counter_count == 10}:
    token_color_run:
      show_tokens:
        tag: tag_lights_grooveline
        color: cyan
        light1: l_grooveline_01
        light2: l_grooveline_02
        light3: l_grooveline_03
        light4: l_grooveline_04
        light5: l_grooveline_05
        light6: l_grooveline_06
        light7: l_grooveline_07
        light8: l_grooveline_08
        light9: l_grooveline_09
        light10: l_grooveline_10
  mode_green_flag_started:
    under_green:
      loops: 0
      sync_ms: 2000
    flash_color:
      speed: 3
      show_tokens:
        led: tag_lights_mode
        color: lime
