#config_version=6

sound_player:
  logicblock_lap_counter_hit: fly_by
  sw_tag_rev: rev
  logicblock_grand_counter_hit: rev
  logicblock_prix_counter_hit: rev
  logicblock_grand_counter_complete: fly_by
  logicblock_prix_counter_complete: fly_by
  sw_tag_swerve: swerve
