#config_version=6

timers:
  lap_to_lap:
    end_value: 0
    start_value: 5
    direction: down
    control_events:
    # start when a lap is recorded
    - event: player_lap_count
      action: restart
