#config_version=6

variable_player:
  ##################
  ## Base Scoring ##
  ##################
  sw_pops:
    score: 10 * current_player.multiplier|block
  s_grooveline_active:
    score: 100 * current_player.multiplier|block
  s_backfire_hole_active{not device.timers.skill_shot.running}:
    score: 500 * current_player.multiplier|block
  s_prix_hole_active:
    score: 100 * current_player.multiplier|block
  s_grand_hole_active:
    score: 100 * current_player.multiplier|block
  s_spinner_active:
    score: 10 * current_player.multiplier|block
  s_save_target_active:
    score: 10 * current_player.multiplier|block
  s_bonus_target_active:
    score: 10 * current_player.multiplier|block
  s_swerve1_active:
    score: 10 * current_player.multiplier|block
  s_swerve2_active:
    score: 10 * current_player.multiplier|block
  s_slingshot1_active:
    score: 10 * current_player.multiplier|block
  s_slingshot2_active:
    score: 10 * current_player.multiplier|block
  s_inlane1_active:
    score: 25 * current_player.multiplier|block
  s_inlane2_active:
    score: 25 * current_player.multiplier|block
  s_outlane1_active:
    score: 50 * current_player.multiplier|block
  s_outlane2_active:
    score: 50 * current_player.multiplier|block

  mode_green_flag_started:
    level_green_flag:
      action: add
      int: 1
    multiplier:
      action: set
      int: 1
  green_flag_degrade_fuel:
    level_fuel:
      action: add
      int: -1
  green_flag_degrade_lube:
    level_lube:
      action: add
      int: -1
  green_flag_degrade_tires:
    level_tires:
      action: add
      int: -1
  green_flag_degrade_all:
    level_fuel:
      action: add
      int: -1
    level_lube:
      action: add
      int: -1
    level_tires:
      action: add
      int: -1
  s_pit_fuel_active:
    level_fuel: 0|block
  s_pit_lube_active:
    level_lube: 0|block
  s_pit_tires_active:
    level_tires: 0|block
  ########################
  ## Counter Peristence ##
  ########################
  # Per docs, "Counters no longer save their
  # state in player variables", so we need
  # to map them manually here
  multiball_stopped:
    multiplier:
      action: set
      int: 1
  logicblock_swerve_counter_complete:
    multiplier:
      action: set
      int: 2
  logicblock_lap_counter_updated:
    lap_counter_count:
      action: set
      int: value
  logicblock_spin_counter_updated:
    spin_counter_count:
      action: set
      int: value
  logicblock_grooveline_counter_updated:
    grooveline_counter_count:
      action: set
      int: value
  logicblock_luxury_counter_updated:
    luxury_counter_count:
      action: set
      int: value
  logicblock_grand_counter_updated:
    grand_counter_count:
      action: set
      int: value
  logicblock_prix_counter_updated:
    prix_counter_count:
      action: set
      int: value
  logicblock_grand_prix_counter_updated:
    grand_prix_counter_count:
      action: set
      int: value
