#config_version=6

# complains about doing this outside of "GAME" modes
#variable_player:
#  s_flipper_eos_2:
#    score: 123

slide_player:
  mode_attract_started:
    attract_slide:
      action: play

