#config_version=6

event_player:
  # 720 is the magic number for the clip played twice (loops: 1)
  # so the gap should be roughly 9 times the total loop duration
  timer_segment_wiggle_timer_tick{ticks % 7200 == 0}: were_going_the_distance
