#config_version=6

sound_player:
  mode_attract_started:
    the_distance:
      track: music
      action: play
      loops: -1
  mode_attract_stopping:
    the_distance:
      track: music
      action: stop
