#config_version=6

mode:
    start_events: ball_starting
    priority: 100

ball_saves:
  ball_start_ball_save:
    active_time: "+10s"
    hurry_up_time: 6s
    timer_start_events: s_shooter_lane_inactive
    auto_launch: true
    balls_to_save: 1
