#config_version=6

hardware:
  platform: smart_virtual

virtual_segment_display_connector:
  segment_displays:
  - segment1
  - segment2
  - segment3
  - segment4

switches:
  # just for testing but needs a number,
  # so using the "fried" coil
  s_activate_playfield:
    number: 0-2-0
    tags:
    - playfield_active

widgets:
  segment_display_widget:
  - type: segment_display_emulator
    name: segment1
    display_type: 7seg
    character_count: 7
    padding: 0.1
    background_color: 11111160
    color: blue
    # character_slant_angle: 0
    character_spacing: 10
    segment_width: 0.09
    # segment_interval: 0.04
    segment_off_color: 222222
    segment_on_color: 73a4ff
    # side_bevel_enabled: false
    # dot_enabled: false
    # comma_enabled: false
    text: ""
    width: 180
    height: 30
    y: 450
    x: 480
  - type: segment_display_emulator
    name: segment2
    display_type: 7seg
    character_count: 7
    padding: 0.1
    background_color: 11111160
    character_spacing: 10
    segment_width: 0.09
    segment_off_color: 222222
    segment_on_color: 73a4ff
    text: ""
    width: 180
    height: 30
    y: 450
    x: 680
  - type: segment_display_emulator
    name: segment3
    display_type: 7seg
    character_count: 7
    padding: 0.1
    background_color: 11111160
    character_spacing: 10
    segment_width: 0.09
    segment_off_color: 222222
    segment_on_color: 73a4ff
    text: ""
    width: 180
    height: 30
    y: 400
    x: 680
  - type: segment_display_emulator
    name: segment4
    display_type: 7seg
    character_count: 7
    padding: 0.1
    background_color: 11111160
    character_spacing: 10
    segment_width: 0.09
    segment_off_color: 222222
    segment_on_color: 73a4ff
    text: ""
    width: 180
    height: 30
    y: 350
    x: 680

widget_player:
  init_done:
    segment_display_widget:
      widget_settings:
        # z: -1 is "always on top" per
        # https://missionpinball.org/latest/mc/widgets/layers/
        z: -1

# So a dev/test game starts with 3 balls in the trough
virtual_platform_start_active_switches:
- s_trough1
- s_trough2
- s_trough3
