#config_version=6

hardware:
  platform: smart_virtual

# So a dev/test game starts with balls in the trough
virtual_platform_start_active_switches:
- s_trough1
- s_trough2
- s_trough3

# virtual_segment_display_connector:
#   segment_displays:
#   # Just one display for dev (for now)
#   - display1

slides:
  virtual_segment_display1:
    widgets:
      - type: segment_display_emulator
        name: display1
        character_count: 7
        character_slant_angle: 0
        character_spacing: 20
        segment_width: 0.11
        segment_interval: 0.04
        segment_off_color: 4b4c4a30
        segment_on_color: fe961bff
        side_bevel_enabled: true
        dot_enabled: true
        comma_enabled: true
        text: "1234567"
        width: 600
        height: 150
        y: 100

slide_player:
  init_done: virtual_segment_display1
