#config_version=6

mode:
  priority: 10000
  start_events:
  - ball_ending{current_player.luxury_counter_count > 0 or current_player.lap_count > 0}
  stop_events:
  - ball_starting

mode_settings:
  display_delay_ms: 4000
  end_bonus_event: bonus_show_ended
  bonus_entries:
  # display in the order here
  - event: bonus_main
    score: 10000
    player_score_entry: luxury_counter_count
    skip_if_zero: false
  # the name of the event the bonus will post
  - event: bonus_lap
    # the value to add to the score per counted event
    score: 1000
    # what is multiplied by the score value
    player_score_entry: lap_count
    skip_if_zero: false

slides:
  bonus_start_slide:
    display_delay_ms: 1000
    widgets:
    - type: text
      font_size: 120
      x: middle
      y: middle
      text: "End of Ball Bonus"
      color: cyan
  bonus_main_slide:
    display_delay_ms: 8000
    widgets:
    - type: text
      font_size: 90
      x: middle
      y: middle + 10%
      text: "Bonus"
      color: pink
    - type: text
      font_size: 140
      text: (score)
      x: middle
      y: middle - 10%
  bonus_lap_slide:
    widgets:
    - type: text
      font_size: 90
      x: middle
      y: middle + 10%
      text: "Laps"
      color: pink
    - type: text
      font_size: 110
      text: (score)
      x: middle
      y: middle - 10%
  bonus_total_slide:
    widgets:
    - type: text
      font_size: 110
      x: middle
      y: middle + 10%
      text: "Total Bonus"
      color: cyan
    - type: text
      font_size: 140
      text: (score)
      x: middle
      y: middle - 10%
      color: pink

slide_player:
  mode_bonus_started: bonus_start_slide
  bonus_lap: bonus_lap_slide
  bonus_main: bonus_main_slide
  bonus_total: bonus_total_slide

sound_player:
  mode_bonus_started:
    quote:
      action: play
      loops: 0
      volume: 0.9
    pit_ambience:
      action: play
      loops: -1
      volume: 0.6

show_player:
  slide_bonus_main_slide_active:
    bonus_main:
      action: play
      loops: 0
      # start at 11 to compensate for 0 index
      start_step: (11 - current_player.luxury_counter_count)
  bonus_total:
    bonus_end:
      action: play
      loops: 0
