#config_version=6

mode:
  start_events:
  - logicblock_grooveline_counter_complete
  stop_events:
  - multiball_grooveline_ended
  restart_on_next_ball: false
  priority: 200

multiballs:
  grooveline:
    ball_count: 1
    ball_count_type: add
    shoot_again: 15s
    start_events: mode_grooveline_started
    # Making 3 laps adds 1 ball
    add_a_ball_events:
    - player_grooveline_counter_count{current_player.grooveline_counter_count == 3}
