#config_version=6

multiballs:
  grooveline:
    ball_count: 2
    ball_count_type: total
    shoot_again: 0
    add_a_ball_shoot_again: 0
    start_events:
    - mode_grooveline_started
    stop_events:
    - multiball_grooveline_ended
    # Making 3 laps adds 1 ball
    add_a_ball_events:
    - player_grooveline_counter_count{current_player.grooveline_counter_count == 3}
