#config_version=6

multiballs:
  grooveline:
    ball_count: 2
    ball_count_type: total
    shoot_again: 0s
    enable_events:
    - mode_grooveline_starting
    start_events:
    - mode_grooveline_started
    stop_events:
    - mode_grooveline_stopping
