#config_version=6

multiballs:
  grooveline:
    ball_count: 2
    ball_count_type: total
    shoot_again: 0s
    add_a_ball_shoot_again: 0s
    enable_events:
    - mode_grooveline_starting
    start_events:
    - mode_grooveline_started
    stop_events:
    - mode_grooveline_stopping
    # Making 3 laps adds 1 ball
    add_a_ball_events:
    - player_grooveline_counter_count{current_player.grooveline_counter_count % 3 == 0}
    tags:
    - multiball
