#config_version=6

sound_player:
  mode_grooveline_started:
    grooveline_starting:
      action: play
    groove_thing:
      action: play
      loops: -1
  mode_grooveline_will_stop:
    groove_thing:
      action: stop
