#config_version=6

hardware:
 platform: opp
 driverboards: gen2
 lights: opp

opp:
  baud: 115200
  ports: /dev/cu.usbmodem101
  chains:
    0: /dev/cu.usbmodem101

lights:
  l_backbox_match_00:
    subtype: matrix
    number: 0-0-0
  l_grooveline_lit:
    subtype: matrix
    # number: 0-2-0 <-- fails light number duplication check without
    #   https://github.com/missionpinball/mpf/pull/1868 fix - could
    #   be other issues with this fix though
    number: 0-2-0 # <-- boots
