#config_version=6

config:
- common/mpf.yaml
- common/assets.yaml
- common/ball_devices.yaml
- common/coils.yaml
- common/displays.yaml
- common/flippers.yaml
- common/game.yaml
- common/keyboard.yaml
- common/lights.yaml
- common/modes.yaml
- common/playfields.yaml
- common/slides.yaml
- common/sounds.yaml
- common/sound_player.yaml
- common/sound_system.yaml
- common/sound_pools.yaml
- common/switches.yaml
- common/variables.yaml
- common/widgets.yaml
- common/shot_profiles.yaml
- common/custom_code.yaml
