#config_version=6

config:
- common/animations.yaml
- common/assets.yaml
- common/autofire_coils.yaml
- common/ball_devices.yaml
- common/coil_player.yaml
- common/coils.yaml
- common/custom_code.yaml
- common/displays.yaml
- common/diverters.yaml
- common/flippers.yaml
- common/game.yaml
- common/info_lights.yaml
- common/keyboard.yaml
- common/lights.yaml
- common/modes.yaml
- common/mpf.yaml
- common/named_colors.yaml
- common/playfields.yaml
- common/rgb_leds.yaml
- common/shot_profiles.yaml
- common/show_player.yaml
- common/slides.yaml
- common/sound_player.yaml
- common/sound_pools.yaml
- common/sound_system.yaml
- common/sounds.yaml
- common/spinners.yaml
- common/switches.yaml
- common/variables.yaml
- common/widget_styles.yaml
- common/widgets.yaml
