#config_version=6

config:
- common/ball_devices.yaml
- common/coils.yaml
- common/game.yaml
- common/hardware.yaml
- common/keyboard.yaml
- common/lights.yaml
- common/flippers.yaml
- common/modes.yaml
- common/players.yaml
- common/playfields.yaml
- common/slides.yaml
- common/sound_system.yaml
- common/switches.yaml
- common/variables.yaml
