#config_version=5
hardware:
  platform: opp
  driverboards: gen2
  # single value, so we need to overide
  # platform to opp for all opp lights
  lights: fadecandy
  segment_displays: mypinballs

mypinballs:
  port: /dev/ttyAMA0

segment_displays:
  display1:
    number: 1
  display2:
    number: 2
  display3:
    number: 3
  display4:
    number: 4

fadecandy:

opp:
  debug: true
  baud: 115200
  ports: /dev/ttyACM0

config:
- switches.yaml
- lights.yaml

show_player:
  mode_attract_started:
    first_show:
      action: play
      loops: -1
      speed: 2
