#config_version=5
hardware:
  platform: opp
  driverboards: gen2
  lights: opp

opp:
  debug: true
  baud: 115200
  ports: /dev/ttyACM0

config:
- switches.yaml
- lights.yaml

show_player:
  mode_attract_started:
    first_show:
      action: play
      loops: -1
      speed: 2
