#config_version=5
#info_lights:
#  match_00:
#    light: l_backbox_match_00
#  match_10:
#    light: l_backbox_match_10
#  match_20:
#    light: l_backbox_match_20
#  match_30:
#    light: l_backbox_match_30
#  match_40:
#    light: l_backbox_match_40
#  match_50:
#    light: l_backbox_match_50
#  match_60:
#    light: l_backbox_match_60
#  match_70:
#    light: l_backbox_match_70
#  match_80:
#    light: l_backbox_match_80
#  match_90:
#    light: l_backbox_match_90
#  ball_1:
#    light: l_backbox_ball1
#  ball_2:
#    light: l_backbox_ball2
#  ball_3:
#    light: l_backbox_ball3
#  # this is the number of players
#  # in the game... for "player up",
#  # supposed to use score reel settings
#  # ... might be better to do something custom
#  player_1:
#    light: l_backbox_player_in1
#  player_2:
#    light: l_backbox_player_in2
#  player_3:
#    light: l_backbox_player_in3
#  player_4:
#    light: l_backbox_player_in4
#  tilt:
#    light: l_backbox_tilt
#  game_over:
#    light: l_backbox_game_over
#
#lights:
#  # Board index 0 - Backbox
#  l_backbox_match_00:
#    subtype: matrix
#    number: 0-0
#  l_backbox_match_10:
#    subtype: matrix
#    number: 0-1
#  l_backbox_match_20:
#    subtype: matrix
#    number: 0-2
#  l_backbox_match_30:
#    subtype: matrix
#    number: 0-3
#  l_backbox_match_40:
#    subtype: matrix
#    number: 0-4
#  l_backbox_match_50:
#    subtype: matrix
#    number: 0-5
#  l_backbox_match_60:
#    subtype: matrix
#    number: 0-6
#  l_backbox_match_70:
#    subtype: matrix
#    number: 0-7
#  l_backbox_match_80:
#    subtype: matrix
#    number: 0-8
#  l_backbox_match_90:
#    subtype: matrix
#    number: 0-9
#  l_backbox_player_up1:
#    subtype: matrix
#    number: 0-10
#  l_backbox_player_up2:
#    subtype: matrix
#    number: 0-11
#  l_backbox_player_up3:
#    subtype: matrix
#    number: 0-12
#  l_backbox_player_up4:
#    subtype: matrix
#    number: 0-13
#  l_backbox_players_in1:
#    subtype: matrix
#    number: 0-14
#  l_backbox_players_in2:
#    subtype: matrix
#    number: 0-15
#  l_backbox_players_in3:
#    subtype: matrix
#    number: 0-16
#  l_backbox_players_in4:
#    subtype: matrix
#    number: 0-17
#  l_backbox_game_over:
#    subtype: matrix
#    number: 0-18
#  l_backbox_tilt:
#    subtype: matrix
#    number: 0-19
#  l_backbox_shoot_again:
#    subtype: matrix
#    number: 0-20
#  l_backbox_ball1:
#    subtype: matrix
#    number: 0-21
#  l_backbox_ball2:
#    subtype: matrix
#    number: 0-22
#  l_backbox_ball3:
#    subtype: matrix
#    number: 0-23
#  # Board index 2 - Central Left Playfield
#  l_spinner_lit1:
#    subtype: matrix
#    number: 2-0
#  l_spinner_lane1_01:
#    subtype: matrix
#    number: 2-1
#  l_spinner_lane1_02:
#    subtype: matrix
#    number: 2-2
#  l_spinner_lane1_03:
#    subtype: matrix
#    number: 2-3
#  l_spinner_lane1_04:
#    subtype: matrix
#    number: 2-4
#  l_spinner_lane1_05:
#    subtype: matrix
#    number: 2-5
#  l_spinner_lane1_06:
#    subtype: matrix
#    number: 2-6
#  l_spinner_lane1_07:
#    subtype: matrix
#    number: 2-7
#  l_spinner_lane1_08:
#    subtype: matrix
#    number: 2-8
#  l_spinner_lane1_09:
#    subtype: matrix
#    number: 2-9
#  l_spinner_lane1_10:
#    subtype: matrix
#    number: 2-10
#  l_north_advance1:
#    subtype: matrix
#    number: 2-11
#  l_north_advance2:
#    subtype: matrix
#    number: 2-12
#  l_spinner_lane2_10:
#    subtype: matrix
#    number: 2-13
#  l_spinner_lane2_09:
#    subtype: matrix
#    number: 2-14
#  l_spinner_lane2_08:
#    subtype: matrix
#    number: 2-15
#  l_spinner_lane2_07:
#    subtype: matrix
#    number: 2-16
#  l_spinner_lane2_06:
#    subtype: matrix
#    number: 2-17
#  l_spinner_lane2_05:
#    subtype: matrix
#    number: 2-18
#  l_spinner_lane2_04:
#    subtype: matrix
#    number: 2-19
#  l_spinner_lane2_03:
#    subtype: matrix
#    number: 2-20
#  l_spinner_lane2_02:
#    subtype: matrix
#    number: 2-21
#  l_spinner_lane2_01:
#    subtype: matrix
#    number: 2-22
#  l_spinner_lit2:
#    subtype: matrix
#    number: 2-23
#  # Board index 3 - Central Playfield
#  l_star4:
#    subtype: matrix
#    number: 3-0
#  l_star3:
#    subtype: matrix
#    number: 3-1
#  l_star2:
#    subtype: matrix
#    number: 3-2
#  l_star1:
#    subtype: matrix
#    number: 3-3
#  l_bonus_lane1_01:
#    subtype: matrix
#    number: 3-4
#  l_bonus_lane1_02:
#    subtype: matrix
#    number: 3-5
#  l_bonus_lane1_03:
#    subtype: matrix
#    number: 3-6
#  l_bonus_lane1_04:
#    subtype: matrix
#    number: 3-7
#  l_bonus_lane1_05:
#    subtype: matrix
#    number: 3-8
#  l_bonus_lane1_06:
#    subtype: matrix
#    number: 3-9
#  l_bonus_lane1_07:
#    subtype: matrix
#    number: 3-10
#  l_bonus_lane1_08:
#    subtype: matrix
#    number: 3-11
#  l_bonus_lane1_09:
#    subtype: matrix
#    number: 3-12
#  l_bonus_lane1_10:
#    subtype: matrix
#    number: 3-13
#  # Board index 4 - South Left Playfield
#  l_apron:
#    subtype: matrix
#    number: 4-8
#  l_bottom_outlane1:
#    subtype: matrix
#    number: 4-9
#  l_shoot_again:
#    subtype: matrix
#    number: 4-10
#  l_arrow1a:
#    subtype: matrix
#    number: 4-11
#  l_arrow1b:
#    subtype: matrix
#    number: 4-12
#  l_top_outlane1:
#    subtype: matrix
#    number: 4-13
#  # Board index 5 - South Right Playfield
#  l_bottom_outlane2:
#    subtype: matrix
#    number: 5-0
#  l_arrow2a:
#    subtype: matrix
#    number: 5-1
#  l_arrow2b:
#    subtype: matrix
#    number: 5-2
#  l_top_outlane2:
#    subtype: matrix
#    number: 5-3
#  l_bonus_lane2_01:
#    subtype: matrix
#    number: 5-4
#  l_bonus_lane2_02:
#    subtype: matrix
#    number: 5-5
#  l_bonus_lane2_03:
#    subtype: matrix
#    number: 5-6
#  l_bonus_lane2_04:
#    subtype: matrix
#    number: 5-7
#  l_bonus_lane2_05:
#    subtype: matrix
#    number: 5-8
#  l_bonus_lane2_06:
#    subtype: matrix
#    number: 5-9
#  l_bonus_lane2_07:
#    subtype: matrix
#    number: 5-10
#  l_bonus_lane2_08:
#    subtype: matrix
#    number: 5-11
#  l_bonus_lane2_09:
#    subtype: matrix
#    number: 5-12
#  l_bonus_lane2_10:
#    subtype: matrix
#    number: 5-13
