#config_version=5
switches:
  # Each OPP board can have up to 4 wings
  # positioned counter-clockwise from top-right
  #    -- 000000 || 00 [(1) 0-15 <= 0-8  ][(0) 0-7  <= 0-0  ][IO]
  # USB          ||
  #    -- 000000 || 0 [(2) 0-16 => 0-23 ][(3) 0-24 => 0-31 ]00000

  ##############
  ## Board 00 ##
  ##############

  # No switches

  ###############
  ### Board 01 ##
  ###############
  s_spinner1:
    number: 1-24
  s_north_drop1:
    number: 1-25
  s_north_rollover:
    number: 1-26
  s_north_advance1:
    number: 1-27
  s_north_hole:
    number: 1-28
  s_north_advance2:
    number: 1-29
  s_north_drop2:
    number: 1-30
  # UNUSED 2-31

  ##############
  ## Board 02 ##
  ##############
  s_tilt:
    number: 2-24
  s_coindoor:
    number: 2-25
  s_service_menu:
    number: 2-26
  s_service_down:
    number: 2-27
  s_service_up:
    number: 2-28
  s_service_mode:
    number: 2-29
  # do we need the pop switches?
  s_pop1:
    number: 2-30
  s_pop2:
    number: 2-31

  ##############
  ## Board 03 ##
  ##############
  s_central_advance1:
    number: 3-24
  s_central_hole1:
    number: 3-25
  s_central_drop1:
    number: 3-26
  s_central_drop2:
    number: 3-27
  s_spinner2:
    number: 3-28
  s_central_hole2:
    number: 3-29
  s_central_advance2:
    number: 3-30
  # UNUSED 3-31

  ##############
  ## Board 04 ##
  ##############
  s_flipper_eos1:
    number: 4-16
  s_slingshot1:
    number: 4-17
  s_inlane1:
    number: 4-18
  s_outlane1:
    number: 4-19
  s_flipper1:
    number: 4-20
  # UNUSED 4-21
  # UNUSED 4-22
  # UNUSED 4-23
  s_trough1:
    number: 4-24
  s_trough2:
    number: 4-25
  s_trough3:
    number: 4-26
  s_trough_jam:
    number: 4-27
  # UNUSED 4-28
  # UNUSED 4-29
  # UNUSED 4-30
  # UNUSED 4-31

  ###############
  ### Board 05 ##
  ###############
  s_flipper_eos2:
    number: 5-24
  s_slingshot2:
    number: 5-25
  s_inlane2:
    number: 5-26
  s_outlane2:
    number: 5-27
  s_shooter_lane:
    number: 5-28
  s_flipper2:
    number: 5-29
  # UNUSED 5-30
  # UNUSED 5-31
