#config_version=6

# Find hardware ports with ls /dev/cu.* and ls /dev/tty.*
# as it will change based on how they're plugged in

hardware:
 platform: opp
 driverboards: gen2
 lights: opp
 # single value, so we need to overide
 # platform to opp for all opp lights
 # lights: fadecandy
 segment_displays: mypinballs

opp:
  baud: 115200
  ports: /dev/cu.usbmodem1101, /dev/cu.usbmodem4EC1526B4B001
  chains:
    0: /dev/cu.usbmodem1101
    1: /dev/cu.usbmodem4EC1526B4B001

mypinballs:
  debug: true
  port: /dev/cu.usbmodem1301
  #port: /dev/ttyAMA0
  #port: /dev/ttyACM0
