#config_version=6

multiballs:
  red_line:
    ball_count: 4
    ball_count_type: total
    shoot_again: 60s
    enable_events:
    - mode_red_line_starting
    start_events:
    - mode_red_line_started
    stop_events:
    - mode_red_line_stopping
