#config_version=6

# GOTCHA: Seems like autofire coils cannot be ALSO fired
# from MPF - or at least not OPP?
autofire_coils:
  pop1:
    coil: c_pop1
    switch: s_pop1
  pop2:
    coil: c_pop2
    switch: s_pop2
  slingshot1:
    coil: c_slingshot1
    switch: s_slingshot1
  slingshot2:
    coil: c_slingshot2
    switch: s_slingshot2
