#config_version=6

ball_devices:
  bd_trough:
    ball_switches:
    - s_trough1
    - s_trough2
    - s_trough3
    tags:
    - trough
    - home
    - drain
    auto_fire_on_unexpected_ball: false
    eject_coil: c_trough
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_shooter_lane
    eject_timeouts: 3s
    jam_switch: s_trough_jam
  bd_shooter_lane:
    ball_switches: s_shooter_lane
    eject_timeouts: 3s
    eject_coil: c_auto_kicker
    mechanical_eject: true
  bd_grand_hole:
    ball_switches: s_grand_hole
    eject_coil: c_grand_hole
  bd_prix_hole:
    ball_switches: s_prix_hole
    eject_coil: c_prix_hole
  bd_backfire_hole:
    ball_switches: s_backfire_hole
    eject_coil: c_backfire_hole
