#config_version=6

ball_devices:
  bd_trough:
    tags: trough, home, drain
    jam_switch: s_trough_jam
    # no trough yet, just a placeholder
    ball_switches:
    - s_trough1
    - s_trough2
    eject_coil: c_trough_eject
    eject_targets: bd_shooter_lane

  bd_shooter_lane:
    ball_switches: s_shooter_lane
    mechanical_eject: True
    # eject_coil: c_plunger_lane
