#config_version=6

ball_devices:
  bd_trough:
    #debug: true
    ball_switches:
    - s_trough1
    - s_trough2
    - s_trough3
    tags:
    - trough
    - home
    - drain
    auto_fire_on_unexpected_ball: false
    eject_coil: c_trough
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_shooter_lane
    eject_timeouts: 1s
    jam_switch: s_trough_jam
  bd_shooter_lane:
    ball_switches: s_shooter_lane
    eject_timeouts: 3s
    eject_coil: c_auto_kicker
    player_controlled_eject_event: s_launch_active
