#config_version=6

coils:
  c_auto_kicker:
    number: 5-3
    default_pulse_ms: 20
  c_trough:
    number: 4-2
    default_pulse_ms: 20
  c_flipper1:
    number: 4-0
    default_pulse_ms: 35
    default_hold_power: 0.5
  c_flipper1_hold:
    number: 4-1
    allow_enable: true
  c_flipper2:
    number: 5-0
    default_pulse_ms: 35
    default_hold_power: 0.5
  c_flipper2_hold:
    number: 5-1
    allow_enable: true
