#config_version=6

coils:
  ##########
  ## CAB1 ##
  ##########
  c_knocker:
    number: 0-12
  # 0-13 OPEN
  # 0-14 OPEN
  # 0-15 OPEN

  ##########
  ## CAB2 ##
  ##########
  c_chime1:
    number: 1-0
  c_chime2:
    number: 1-1
  c_chime3:
    number: 1-2
  c_shaker_motor:
    number: 1-3
    default_hold_power: 1

  ###########
  ## MIXED ##
  ###########
  #
  # NO COILS ON BOARD INDEX 2

  ################
  ## PLAYFIELD1 ##
  ################
  c_backfire_hole:
    number: 3-0
  c_tires:
    number: 3-1
  c_oil:
    number: 3-2
  # 3-3 OPEN
  c_pop1:
    number: 3-4
  c_pop2:
    number: 3-5
  c_fuel:
    number: 3-6
  c_prix_hole:
    number: 3-7

  ################
  ## PLAYFIELD2 ##
  ################
  c_disqualifier:
    number: 4-0
  c_grand_hole:
    number: 4-1
  # 4-2 OPEN
  # 4-3 OPEN

  #############
  ## APRON 1 ##
  #############
  c_flipper2:
    number: 5-0
    default_hold_power: 0.5
  c_slingshot2:
    number: 5-1
  # UNUSED 5-2
  c_auto_kicker:
    number: 5-3

  #############
  ## APRON 2 ##
  #############
  c_flipper1:
    number: 6-0
    default_hold_power: 0.5
  c_slingshot1:
    number: 6-1
  # UNUSED 6-2
  c_trough:
    number: 6-3
