#config_version=6

coils:
  c_knocker:
    number: 0-0-12
  c_chime1:
    number: 0-1-0
  c_chime2:
    number: 0-1-1
  c_chime3:
    number: 0-1-2
  c_shaker_motor:
    number: 0-1-3
    default_hold_power: 1
  c_backfire_hole:
    number: 0-3-0
  c_prix_hole:
    number: 0-3-1
  c_pop1:
    number: 0-3-4
  c_pop2:
    number: 0-3-5
  c_fuel:
    number: 0-3-6
  c_disqualifier:
    number: 0-4-0
  c_grand_hole:
    number: 0-4-1
  c_flipper2:
    number: 0-5-0
    default_hold_power: 0.5
  c_slingshot2:
    number: 0-5-1
  c_auto_kicker:
    number: 0-5-3
  c_flipper1:
    number: 0-6-0
    default_hold_power: 0.5
  c_slingshot1:
    number: 0-6-1
  c_trough:
    number: 0-6-3
