#config_version=6

coils:
  # Board index 0 - Wing index 3
  c_chime1:
    number: 0-0-12
  c_chime2:
    number: 0-0-13
  c_chime3:
    number: 0-0-14
  c_shaker_motor:
    number: 0-0-15
    default_hold_power: 1
  # Board index 1 - Wing index 0
  # c_pop1:
  #   number: 0-1-13
  # c_pop2:
  #   number: 0-1-12
  # Board index 1 - Wing index 2
  # NOTHING

  # Board index 1 - Wing index 3
  c_grand_hole:
    number: 0-1-3
  # c_backfire_hole:
  #   number: 0-1-15

  # Board index 2 - Wing index 0
  c_disqualifier_up:
    number: 0-1-0
  # 0-2-1 FRIED
  c_disqualifier_down:
    number: 0-1-2
  # c_prix_hole:
  #   number: 0-1-14

  # Board index 3 - Wing index 0
  # 0-3-0 NOTHING
  c_slingshot2:
    number: 0-2-1
  c_flipper1:
    number: 0-2-2
    default_pulse_ms: 25
#see note on c_flipper1
    default_hold_power: 0.8
  c_auto_kicker:
    number: 0-2-3

  # Board index 4 - Wing index 0
  c_flipper2:
    number: 0-3-0
    default_pulse_ms: 25
#technically the coils mechanically handle
#the switch to low power, but this should be
#enough to hold the flipper up and also kinda
#protect against a shorted EOS switch
    default_hold_power: 0.8
  c_slingshot1:
    number: 0-3-1
  # 0-4-2 EMPTY
  c_trough:
    number: 0-3-3
    default_pulse_ms: 25

  # c_knocker
  # volt meter
