#config_version=6

coils:
  c_chime1:
    number: 0-0-12
  c_chime2:
    number: 0-0-13
  c_chime3:
    number: 0-0-14
  c_shaker_motor:
    number: 0-0-15
    default_hold_power: 1
  c_knocker:
    number: 0-1-0
  c_backfire_hole:
    number: 0-1-1
  c_prix_hole:
    number: 0-1-2
  c_pop1:
    number: 0-1-3
  c_pop2:
    number: 0-1-8
  c_fuel:
    number: 0-1-9
  c_disqualifier:
    number: 0-1-10
  c_grand_hole:
    number: 0-1-11
  c_flipper2:
    number: 0-2-0
    default_hold_power: 0.5
  c_slingshot2:
    number: 0-2-1
  c_auto_kicker:
    number: 0-2-2
  c_flipper1:
    number: 0-2-3
    default_hold_power: 0.5
  c_slingshot1:
    number: 0-3-0
  c_trough:
    number: 0-3-1
