#config_version=6

window:
  title: Grand Prix ’86
  # Per https://www.amazon.com/gp/product/B0CP3DH3LN
  width: 800
  height: 480
  maxfps: 30
  show_cursor: false
  fullscreen: false

displays:
  apron:
    width: 800
    height: 480
    default: true

segment_displays:
  segment1:
    update_method: replace
    number: 1
