#config_version=6

displays:
  apron:
    width: 800
    height: 480
    default: true

segment_displays:
  segment1:
    number: 1
  segment2:
    number: 2
  segment3:
    number: 3
  segment4:
    number: 4
