#config_version=6

displays:
  apron:
    width: 800
    height: 480
    label: Apron
    default: true

window:
  title: Grand Prix ’86
  # Per https://www.amazon.com/gp/product/B0CP3DH3LN
  width: 800
  height: 480
  source_display: apron
  maxfps: 30
  show_cursor: false
  fullscreen: true

segment_displays:
  display1:
    update_method: replace
    number: 1
  # display2:
  #   update_method: replace
  #   number: 2
  # display3:
  #   update_method: replace
  #   number: 3
  # display4:
  #   update_method: replace
  #   number: 4
