#config_version=6

diverters:
  loop_gate:
    activation_coil: c_loop_gate
    type: hold
    activation_time: 2s
    activate_events:
    - s_spinner_active
    # activate on initial ball launch
    - s_shooter_lane_inactive{not mode.green_flag.active}
    deactivate_events:
    - s_grooveline_active
    # hitting ANYTHING following initial ball
    # launch will deactivate (only open for plunge)
    - playfield_active{not mode.green_flag.active}
    targets_when_active: playfield
    cool_down_time: 1s
    enable_events:
    - mode_green_flag_started
    - mode_pit_starting
    disable_events:
    - mode_green_flag_stopped
    # disables itself when it deactivates itself
    # for initial plunge
    - diverter_loop_gate_deactivating{not mode.green_flag.active}
