#config_version=6

# Start game with 's' key
# Then 'l' to launch, 'f' to fuel up

keyboard:
  #########################
  ## Testing / Debugging ##
  #########################
  shift+l:
    event: light_all
  ctrl+q:
    event: coil_pop1
  ctrl+w:
    event: coil_pop2
  ctrl+e:
    event: coil_backfire
  ctrl+r:
    event: coil_prix
  ctrl+t:
    event: coil_grand
  ctrl+y:
    event: coil_chime1
  ctrl+u:
    event: coil_chime2
  ctrl+i:
    event: coil_chime3
  ctrl+o:
    event: coil_shaker
  ctrl+p:
    event: coil_disqualifier_up
  ctrl+a:
    event: coil_disqualifier_down
  ctrl+s:
    event: coil_auto_kicker
  ctrl+d:
    event: coil_flipper1
  ctrl+f:
    event: coil_flipper2
  ctrl+g:
    event: coil_trough

  ####################
  ## Trough / Drain ##
  ####################
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough_jam
    toggle: true

  #############
  ## Control ##
  #############
  s:
    switch: s_start
  l:
    switch: s_launch

  # Flippers
  z:
    switch: s_flipper2
  "/":
    switch: s_flipper1

  ########################
  ## Switches / Targets ##
  ########################
  m:
    switch: s_multiball_target

  # Scoops & grouped switched
  b+h:
    switch: s_backfire_hole

  g+h:
    switch: s_grand_hole
  g+t:
    switch: s_save_target

  p+h:
    switch: s_prix_hole
  p+t:
    switch: s_save_target

  # Pit Resources
  f:
    switch: s_pit_fuel
  o:
    switch: s_pit_lube
  t:
    switch: s_pit_tires

  # Lap sequence (spinner, grooveline)
  ",":
    switch: s_spinner
  ".":
    switch: s_grooveline

  "[":
    switch: s_pop1
  "]":
    switch: s_pop2
  ";":
    switch: s_slingshot2
  "'":
    switch: s_slingshot1

  #####################
  ## MODE ACTIVATION ##
  #####################
  shift-h:
    event: start_high_score
  # Luxury
  shift-l:
    event: luxury_qualifier_hit
  # Grand Prix
  shift-p:
    event: grand_prix_qualifier_hit
  shift-g:
    event: grooveline_qualifier_hit
