#config_version=6

keyboard:
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough_jam
    toggle: true
  s:
    switch: s_start
  l:
    switch: s_shooter_lane
  a:
    switch: s_grand_hole
  f:
    switch: s_qualifier1
  o:
    switch: s_qualifier2
  t:
    switch: s_qualifier3
