#config_version=6

# Start game with 's' key
# Then 'l' to launch, 'f' to fuel up
#

keyboard:
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough_jam
    toggle: true
  s:
    switch: s_start
  l:
    switch: s_launch
  g:
    switch: s_grand_hole
  b:
    switch: s_backfire_hole
  p:
    switch: s_prix_hole
  f:
    switch: s_fuel
  o:
    switch: s_oil
  t:
    switch: s_tires
  m:
    switch: s_multiball_target
  # the next two switches (spinner, grooveline)
  # in sequence trigger a "lap"
  ",":
    switch: s_spinner
  ".":
    switch: s_grooveline
  z:
    switch: s_flipper2
  "/":
    switch: s_flipper1
  "[":
    switch: s_pop1
  "]":
    switch: s_pop2
  "-":
    switch: s_slingshot2
  "=":
    switch: s_slingshot1
  "'":
    event: light_all
  q:
    event: start_high_score
