#config_version=6
lights:
  #################
  # Board BACKBOX #
  #################

  l_backbox_match_00:
    subtype: matrix
    number: 0-0
    platform: opp
  l_backbox_match_10:
    subtype: matrix
    number: 0-1
    platform: opp
  l_backbox_match_20:
    subtype: matrix
    number: 0-2
    platform: opp
  l_backbox_match_30:
    subtype: matrix
    number: 0-3
    platform: opp
  l_backbox_match_40:
    subtype: matrix
    number: 0-4
    platform: opp
  l_backbox_match_50:
    subtype: matrix
    number: 0-5
    platform: opp
  l_backbox_match_60:
    subtype: matrix
    number: 0-6
    platform: opp
  l_backbox_match_70:
    subtype: matrix
    number: 0-7
    platform: opp
  l_backbox_match_80:
    subtype: matrix
    number: 0-8
    platform: opp
  l_backbox_match_90:
    subtype: matrix
    number: 0-9
    platform: opp
  l_backbox_player_up1:
    subtype: matrix
    number: 0-10
    platform: opp
  l_backbox_player_up2:
    subtype: matrix
    number: 0-11
    platform: opp
  l_backbox_player_up3:
    subtype: matrix
    number: 0-12
    platform: opp
  l_backbox_player_up4:
    subtype: matrix
    number: 0-13
    platform: opp
  l_backbox_players_in1:
    subtype: matrix
    number: 0-14
    platform: opp
  l_backbox_players_in2:
    subtype: matrix
    number: 0-15
    platform: opp
  l_backbox_players_in3:
    subtype: matrix
    number: 0-16
    platform: opp
  l_backbox_players_in4:
    subtype: matrix
    number: 0-17
    platform: opp
  l_backbox_game_over:
    subtype: matrix
    number: 0-18
    platform: opp
  l_backbox_tilt:
    subtype: matrix
    number: 0-19
    platform: opp
  l_backbox_shoot_again:
    subtype: matrix
    number: 0-20
    platform: opp
  l_backbox_ball1:
    subtype: matrix
    number: 0-21
    platform: opp
  l_backbox_ball2:
    subtype: matrix
    number: 0-22
    platform: opp
  l_backbox_ball3:
    subtype: matrix
    number: 0-23
    platform: opp

  ####################
  # Board PLAYFIELD1 #
  ####################

  # NOTE: Only the 3rd wing is wired
  #       for incandescent / 6v drivers
  l_gi:
    subtype: matrix
    number: 1-16
  # UNUSED 1-17
  # UNUSED 1-18
  # UNUSED 1-19
  # UNUSED 1-20
  # UNUSED 1-21
  # UNUSED 1-22

  # NOTE: this is a workaround for the mini
  #       coils which only require 5v
  x_loop_gate:
    subtype: matrix
    number: 1-23

  #############
  # Board CAB #
  #############

  l_grooveline_lit:
    subtype: matrix
    number: 2-0
  l_grooveline_01:
    subtype: matrix
    number: 2-1
  l_grooveline_02:
    subtype: matrix
    number: 2-2
  l_grooveline_03:
    subtype: matrix
    number: 2-3
  l_grooveline_04:
    subtype: matrix
    number: 2-4
  l_grooveline_05:
    subtype: matrix
    number: 2-5
  l_grooveline_06:
    subtype: matrix
    number: 2-6
  l_grooveline_07:
    subtype: matrix
    number: 2-7
  l_grooveline_08:
    subtype: matrix
    number: 2-8
  l_grooveline_09:
    subtype: matrix
    number: 2-9
  l_grooveline_10:
    subtype: matrix
    number: 2-10
  l_north_advance1:
    subtype: matrix
    number: 2-11
  l_north_advance2:
    subtype: matrix
    number: 2-12
  l_spinner_10:
    subtype: matrix
    number: 2-13
  l_spinner_09:
    subtype: matrix
    number: 2-14
  l_spinner_08:
    subtype: matrix
    number: 2-15
  l_spinner_07:
    subtype: matrix
    number: 2-16
  l_spinner_06:
    subtype: matrix
    number: 2-17
  l_spinner_05:
    subtype: matrix
    number: 2-18
  l_spinner_04:
    subtype: matrix
    number: 2-19
  l_spinner_03:
    subtype: matrix
    number: 2-20
  l_spinner_02:
    subtype: matrix
    number: 2-21
  l_spinner_01:
    subtype: matrix
    number: 2-22
  l_spinner_lit:
    subtype: matrix
    number: 2-23

  ####################
  # Board PLAYFIELD2 #
  ####################

  l_star4:
    subtype: matrix
    number: 3-8
  l_star3:
    subtype: matrix
    number: 3-9
  l_star2:
    subtype: matrix
    number: 3-10
  l_star1:
    subtype: matrix
    number: 3-11
  l_grand_01:
    subtype: matrix
    number: 3-12
  l_grand_02:
    subtype: matrix
    number: 3-13
  l_grand_03:
    subtype: matrix
    number: 3-14
  l_grand_04:
    subtype: matrix
    number: 3-15
  l_grand_05:
    subtype: matrix
    number: 3-16
  l_pit_01:
    subtype: matrix
    number: 3-17
  l_pit_02:
    subtype: matrix
    number: 3-18
  l_pit_03:
    subtype: matrix
    number: 3-19
  # UNUSED 3-20
  # UNUSED 3-21
  # UNUSED 3-22
  # UNUSED 3-23

  ################
  # Board APRON1 #
  ################

  l_apron:
    subtype: matrix
    number: 4-8
  l_bottom_outlane1:
    subtype: matrix
    number: 4-9
  l_shoot_again:
    subtype: matrix
    number: 4-10
  l_arrow1a:
    subtype: matrix
    number: 4-11
  l_arrow1b:
    subtype: matrix
    number: 4-12
  l_top_outlane1:
    subtype: matrix
    number: 4-13
  # UNUSED 4-14
  # UNUSED 4-15

  ################
  # Board APRON2 #
  ################

  l_bottom_outlane2:
    subtype: matrix
    number: 5-8
  l_arrow2a:
    subtype: matrix
    number: 5-9
  l_arrow2b:
    subtype: matrix
    number: 5-10
  l_top_outlane2:
    subtype: matrix
    number: 5-11
  l_prix_04:
    subtype: matrix
    number: 5-12
  l_prix_03:
    subtype: matrix
    number: 5-13
  l_prix_02:
    subtype: matrix
    number: 5-14
  l_prix_01:
    subtype: matrix
    number: 5-15
  l_lap_03:
    subtype: matrix
    number: 5-16
  l_lap_02:
    subtype: matrix
    number: 5-17
  l_lap_01:
    subtype: matrix
    number: 5-18
  # UNUSED 5-19
  # UNUSED 5-20
  # UNUSED 5-21
  # UNUSED 5-22
  # UNUSED 5-23

  ###############
  ## Fade Candy #
  ###############

  rgb_448:
    number: 7-0

info_lights:
  match_00:
    light: l_backbox_match_00
  match_10:
    light: l_backbox_match_10
  match_20:
    light: l_backbox_match_20
  match_30:
    light: l_backbox_match_30
  match_40:
    light: l_backbox_match_40
  match_50:
    light: l_backbox_match_50
  match_60:
    light: l_backbox_match_60
  match_70:
    light: l_backbox_match_70
  match_80:
    light: l_backbox_match_80
  match_90:
    light: l_backbox_match_90
  ball_1:
    light: l_backbox_ball1
  ball_2:
    light: l_backbox_ball2
  ball_3:
    light: l_backbox_ball3
  # this is the number of players
  # in the game... for "player up",
  # supposed to use score reel settings
  # ... might be better to do something custom
  player_1:
    light: l_backbox_players_in1
  player_2:
    light: l_backbox_players_in2
  player_3:
    light: l_backbox_players_in3
  player_4:
    light: l_backbox_players_in4
  game_over:
    light: l_backbox_game_over
  tilt:
    light: l_backbox_tilt
