#config_version=6

lights:
  l_backbox_match_00:
    subtype: matrix
    number: 0-0-0
    tags:
    - tag_lights_match
    - tag_lights_state
    - tag_lights
  l_backbox_match_10:
    subtype: matrix
    number: 0-0-1
    tags:
    - tag_lights_match
    - tag_lights_state
    - tag_lights
    - tag_match02
  l_backbox_match_20:
    subtype: matrix
    number: 0-0-2
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_match
    - tag_match03
  l_backbox_match_30:
    subtype: matrix
    number: 0-0-3
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
  l_backbox_match_40:
    subtype: matrix
    number: 0-0-4
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
  l_backbox_match_50:
    subtype: matrix
    number: 0-0-5
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
  l_backbox_match_60:
    subtype: matrix
    number: 0-0-6
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
  l_backbox_match_70:
    subtype: matrix
    number: 0-0-7
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
    - tag_lights_state
  l_backbox_match_80:
    subtype: matrix
    number: 0-0-8
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
  l_backbox_match_90:
    subtype: matrix
    number: 0-0-9
    tags:
    - tag_lights
    - tag_lights_match
    - tag_lights_state
  l_tach:
    subtype: matrix
    number: 0-0-11
  l_backbox_players_in1:
    subtype: matrix
    number: 0-0-14
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_players_in2:
    subtype: matrix
    number: 0-0-15
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_players_in3:
    subtype: matrix
    number: 0-0-16
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_players_in4:
    subtype: matrix
    number: 0-0-17
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_game_over:
    subtype: matrix
    number: 0-0-18
    tags:
    - tag_lights
    - tag_lights_info_lights
  l_backbox_tilt:
    subtype: matrix
    number: 0-0-19
    tags:
    - tag_lights_info_lights
    - tag_lights
  l_backbox_shoot_again:
    subtype: matrix
    number: 0-0-20
    tags:
    - tag_lights
    - tag_lights_info_lights
    - tag_shoot_again
  l_backbox_ball1:
    subtype: matrix
    number: 0-0-21
    tags:
    - tag_lights
    - tag_lights_active_ball
    - tag_lights_info_lights
  l_backbox_ball2:
    subtype: matrix
    number: 0-0-22
    tags:
    - tag_lights
    - tag_lights_active_ball
    - tag_lights_info_lights
  l_backbox_ball3:
    subtype: matrix
    number: 0-0-23
    tags:
    - tag_lights
    - tag_lights_active_ball
    - tag_lights_info_lights

  # BOARD INDEX 1 (first playfield)

  # 0-1-16 might be bad
  l_swerve1:
    subtype: matrix
    number: 0-1-17
    tags:
    - tag_lights
    - tag_lights_swerve
  l_swerve2:
    subtype: matrix
    number: 0-1-18
    tags:
    - tag_lights
    - tag_lights_swerve
  l_bonus_10:
    subtype: matrix
    number: 0-1-19
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  # 1-20 might be bad
  l_bonus_08:
    subtype: matrix
    number: 0-1-23
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_multiball:
    subtype: matrix
    number: 0-1-21
    tags:
    - tag_lights
  l_grand_03:
    subtype: matrix
    number: 0-1-22
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_lights_grand_prix
    - tag_lights_state

  # BOARD INDEX 2

  l_grand_05:
    subtype: matrix
    number: 0-2-8
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_lights_grand_prix
    - tag_lights_state
  l_bottom_outlane1:
    subtype: matrix
    number: 0-2-9
    tags:
    - tag_lights
    - tag_lights_outlane
    - tag_lights_state
  l_multiplier_01:
    subtype: matrix
    number: 0-2-11
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_multiplier
  l_multiplier_02:
    subtype: matrix
    number: 0-2-12
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_multiplier
  l_multiplier_03:
    subtype: matrix
    number: 0-2-13
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_multiplier
  l_top_outlane1:
    subtype: matrix
    number: 0-2-14
    tags:
    - tag_lights
    - tag_lights_outlane
  l_luxury:
    subtype: matrix
    number: 0-2-15
    tags:
    - tag_lights

  # BOARD INDEX 3

  # 0-3-18 might be disconnected inline
  l_bonus_01:
    subtype: matrix
    number: 0-3-16
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_02:
    subtype: matrix
    number: 0-3-17
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_03:
    subtype: matrix
    number: 0-3-18
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_04:
    subtype: matrix
    number: 0-3-19
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_05:
    subtype: matrix
    number: 0-3-20
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_06:
    subtype: matrix
    number: 0-3-21
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_07:
    subtype: matrix
    number: 0-3-22
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  l_bonus_09:
    subtype: matrix
    number: 0-3-23
    tags:
    - tag_lights
    - tag_lights_state
    - tag_lights_spinner
  # l_gi:
  #   subtype: matrix
  #   number: 0-1-22
  #   tags:
  #   - tag_lights
  l_signal4: # red line
    subtype: matrix
    number: 0-1-8
    tags:
    - tag_lights
    - tag_lights_signal
  l_signal3: # grand prix
    subtype: matrix
    number: 0-1-9
    tags:
    - tag_lights
    - tag_lights_signal
  l_signal2: # luxury
    subtype: matrix
    number: 0-1-10
    tags:
    - tag_lights
    - tag_lights_signal
  l_signal1: # grooveline
    subtype: matrix
    number: 0-1-11
    tags:
    - tag_lights
    - tag_lights_signal
  l_grand_01:
    subtype: matrix
    number: 0-1-12
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_lights_grand_prix
    - tag_lights_state
  l_grand_02:
    subtype: matrix
    number: 0-1-13
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_lights_grand_prix
    - tag_lights_state
  l_grand_04:
    subtype: matrix
    number: 0-1-15
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_lights_grand_prix
    - tag_lights_state
  l_shoot_again:
    subtype: matrix
    number: 0-2-10
    tags:
    - tag_lights
    - tag_shoot_again
  l_bottom_outlane2:
    subtype: matrix
    number: 0-3-8
    tags:
    - tag_lights
    - tag_lights_outlane
  l_top_outlane2:
    subtype: matrix
    number: 0-3-11
    tags:
    - tag_lights
    - tag_lights_outlane
  l_prix_04:
    subtype: matrix
    number: 0-3-12
    tags:
    - tag_lights
    - tag_lights_prix
    - tag_lights_grand_prix
    - tag_lights_state
  l_prix_03:
    subtype: matrix
    number: 0-3-13
    tags:
    - tag_lights
    - tag_lights_prix
    - tag_lights_grand_prix
    - tag_lights_state
  l_prix_02:
    subtype: matrix
    number: 0-3-14
    tags:
    - tag_lights
    - tag_lights_prix
    - tag_lights_grand_prix
    - tag_lights_state
  l_prix_01:
    subtype: matrix
    number: 0-3-15
    tags:
    - tag_lights
    - tag_lights_prix
    - tag_lights_grand_prix
    - tag_lights_state
