#config_version=6

lights:
  #################
  # Board BACKBOX #
  #################

  l_backbox_match_00:
    subtype: matrix
    number: 0-0-0
    tags:
    - tag_lights_match
    - tag_lights
  l_backbox_match_10:
    subtype: matrix
    number: 0-0-1
    tags:
    - tag_lights_match
    - tag_lights
  l_backbox_match_20:
    subtype: matrix
    number: 0-0-2
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_30:
    subtype: matrix
    number: 0-0-3
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_40:
    subtype: matrix
    number: 0-0-4
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_50:
    subtype: matrix
    number: 0-0-5
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_60:
    subtype: matrix
    number: 0-0-6
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_70:
    subtype: matrix
    number: 0-0-7
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_80:
    subtype: matrix
    number: 0-0-8
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_match_90:
    subtype: matrix
    number: 0-0-9
    tags:
    - tag_lights
    - tag_lights_match
  l_backbox_player_up1:
    subtype: matrix
    number: 0-0-10
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_player_up2:
    subtype: matrix
    number: 0-0-11
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_player_up3:
    subtype: matrix
    number: 0-0-12
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_player_up4:
    subtype: matrix
    number: 0-0-13
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_players_in1:
    subtype: matrix
    number: 0-0-14
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_players_in2:
    subtype: matrix
    number: 0-0-15
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_players_in3:
    subtype: matrix
    number: 0-0-16
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_players_in4:
    subtype: matrix
    number: 0-0-17
    tags:
    - tag_lights
    - tag_lights_players_in
    - tag_lights_info_lights
  l_backbox_game_over:
    subtype: matrix
    number: 0-0-18
    tags:
    - tag_lights
    - tag_lights_info_lights
  l_backbox_tilt:
    subtype: matrix
    number: 0-0-19
    tags:
    - tag_lights_info_lights
    - tag_lights
  l_backbox_shoot_again:
    subtype: matrix
    number: 0-0-20
    tags:
    - tag_lights
    - tag_lights_info_lights
  l_backbox_ball1:
    subtype: matrix
    number: 0-0-21
    tags:
    - tag_lights
    - tag_lights_active_ball
    - tag_lights_info_lights
  l_backbox_ball2:
    subtype: matrix
    number: 0-0-22
    tags:
    - tag_lights
    - tag_lights_active_ball
    - tag_lights_info_lights
  l_backbox_ball3:
    subtype: matrix
    number: 0-0-23
    tags:
    - tag_lights
    - tag_lights_active_ball
    - tag_lights_info_lights

  ####################
  # Board PLAYFIELD1 #
  ####################

  # NOTE: Only the 3rd wing is wired
  #       for incandescent / 6v drivers
  l_gi:
    subtype: matrix
    number: 0-3-16
    tags:
    - tag_lights

  # UNUSED 1-17
  # UNUSED 1-18
  # UNUSED 1-19
  # UNUSED 1-20
  # UNUSED 1-21
  # UNUSED 1-22

  # NOTE: this is a workaround for the mini
  #       coils which only require 5v
  x_loop_gate:
    subtype: matrix
    number: 0-3-23
    tags:
    - tag_lights

  #############
  # Board CAB #
  #############

  # UNUSED 2-0
  l_swerve1:
    subtype: matrix
    number: 0-2-11
    tags:
    - tag_lights
    - tag_lights_swerve
  l_swerve2:
    subtype: matrix
    number: 0-2-12
    tags:
    - tag_lights
    - tag_lights_swerve
  l_spinner_10:
    subtype: matrix
    number: 0-2-13
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_09:
    subtype: matrix
    number: 0-2-14
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_08:
    subtype: matrix
    number: 0-2-15
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_07:
    subtype: matrix
    number: 0-2-16
    tags:
    - tag_lights_spinner
  l_spinner_06:
    subtype: matrix
    number: 0-2-17
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_05:
    subtype: matrix
    number: 0-2-18
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_04:
    subtype: matrix
    number: 0-2-19
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_03:
    subtype: matrix
    number: 0-2-20
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_02:
    subtype: matrix
    number: 0-2-21
    tags:
    - tag_lights
    - tag_lights_spinner
  l_spinner_01:
    subtype: matrix
    number: 0-2-22
    tags:
    - tag_lights
    - tag_lights_spinner
  l_luxury:
    subtype: matrix
    number: 0-2-23
    tags:
    - tag_lights

  ####################
  # Board PLAYFIELD2 #
  ####################

  l_signal4: # red line
    subtype: matrix
    number: 0-4-8
    tags:
    - tag_lights
    - tag_lights_signal
  l_signal3: # grand prix
    subtype: matrix
    number: 0-4-9
    tags:
    - tag_lights
    - tag_lights_signal
  l_signal2: # luxury
    subtype: matrix
    number: 0-4-10
    tags:
    - tag_lights
    - tag_lights_signal
  l_signal1: # grooveline
    subtype: matrix
    number: 0-4-11
    tags:
    - tag_lights
    - tag_lights_signal
  l_grand_01:
    subtype: matrix
    number: 0-4-12
    tags:
    - tag_lights
    - tag_lights_grand
  l_grand_02:
    subtype: matrix
    number: 0-4-13
    tags:
    - tag_lights
    - tag_lights_grand
  l_grand_03:
    subtype: matrix
    number: 0-4-14
    tags:
    - tag_lights
    - tag_lights_grand
  l_grand_04:
    subtype: matrix
    number: 0-4-15
    tags:
    - tag_lights
    - tag_lights_grand
  l_grand_05:
    subtype: matrix
    number: 0-4-16
    tags:
    - tag_lights
    - tag_lights_grand
  l_pit_tires:
    subtype: matrix
    number: 0-4-17
    tags:
    - tag_lights
    - tag_lights_pit
  l_pit_lube:
    subtype: matrix
    number: 0-4-18
    tags:
    - tag_lights
    - tag_lights_pit
  l_pit_fuel:
    subtype: matrix
    number: 0-4-19
    tags:
    - tag_lights
    - tag_lights_pit
  l_multiball:
    subtype: matrix
    number: 0-4-21
    tags:
    - tag_lights
  # UNUSED 4-21
  # UNUSED 4-22
  # UNUSED 4-23

  ################
  # Board APRON1 #
  ################

  l_apron:
    subtype: matrix
    number: 0-5-8
    tags:
    - tag_lights
  l_bottom_outlane1:
    subtype: matrix
    number: 0-5-9
    tags:
    - tag_lights
    - tag_lights_outlane
  l_shoot_again:
    subtype: matrix
    number: 0-5-10
    tags:
    - tag_lights
  l_arrow1a:
    subtype: matrix
    number: 0-5-11
    tags:
    - tag_lights
    - tag_lights_arrow
  l_arrow1b:
    subtype: matrix
    number: 0-5-12
    tags:
    - tag_lights
    - tag_lights_arrow
  l_top_outlane1:
    subtype: matrix
    number: 0-5-13
    tags:
    - tag_lights
    - tag_lights_outlane
  # UNUSED 5-14
  # UNUSED 5-15

  ################
  # Board APRON2 #
  ################

  l_bottom_outlane2:
    subtype: matrix
    number: 0-6-8
    tags:
    - tag_lights
    - tag_lights_outlane
  l_arrow2a:
    subtype: matrix
    number: 0-6-9
    tags:
    - tag_lights
    - tag_lights_arrow
  l_arrow2b:
    subtype: matrix
    number: 0-6-10
    tags:
    - tag_lights
    - tag_lights_arrow
  l_top_outlane2:
    subtype: matrix
    number: 0-6-11
    tags:
    - tag_lights
    - tag_lights_outlane
  l_prix_04:
    subtype: matrix
    number: 0-6-12
    tags:
    - tag_lights
    - tag_lights_prix
  l_prix_03:
    subtype: matrix
    number: 0-6-13
    tags:
    - tag_lights
    - tag_lights_prix
  l_prix_02:
    subtype: matrix
    number: 0-6-14
    tags:
    - tag_lights
    - tag_lights_prix
  l_prix_01:
    subtype: matrix
    number: 0-6-15
    tags:
    - tag_lights
    - tag_lights_prix
  l_multiplier_03:
    subtype: matrix
    number: 0-6-16
    tags:
    - tag_lights
    - tag_lights_multiplier
  l_multiplier_02:
    subtype: matrix
    number: 0-6-17
    tags:
    - tag_lights
    - tag_lights_multiplier
  l_multiplier_01:
    subtype: matrix
    number: 0-6-18
    tags:
    - tag_lights
    - tag_lights_multiplier
  # UNUSED 6-19
  # UNUSED 6-20
  # UNUSED 6-21
  # UNUSED 6-22
  # UNUSED 6-23

  #######################
  ## SweetLED (Neopixel #
  #######################

  l_backfire:
    subtype: led
    number: 1-0-0
    tags:
    - tag_lights
    - tag_lights_grooveline
  #   number: 7-0
  l_grooveline_01:
    subtype: led
    number: 1-0-1
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_02:
    subtype: led
    number: 1-0-2
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_03:
    subtype: led
    number: 1-0-3
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_04:
    subtype: led
    number: 1-0-4
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_05:
    subtype: led
    number: 1-0-5
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_06:
    subtype: led
    number: 1-0-6
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_07:
    subtype: led
    number: 1-0-7
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_08:
    subtype: led
    number: 1-0-8
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_09:
    subtype: led
    number: 1-0-9
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_10:
    subtype: led
    number: 1-0-10
    tags:
    - tag_lights
    - tag_lights_grooveline
