#config_version=6

named_colors:
  cyan: 00E9FF
  aqua: 01FFCC # also, full fuel + full lube
  pink: DF02E3 # also, low fuel
  magenta: C661ED # also, low tires
  lime: 57F135 # also, full tires or positive things
  orange: FF7F35 # also, low lube
  red: FF003B # also, negative things
