#config_version=6

segment_display_player:
  update_segment_display_score:
    segment1:
      flashing: off
      color: 00acf0
      text: (player1|score)

sound_player:
  mode_attract_started:
    rad_racer:
      track: music
      action: play
      loops: -1
  mode_attract_stopped:
    rad_racer:
      track: music
      action: stop

slide_player:
  mode_green_flag_started: green_flag_slide
