#config_version=6

segment_display_player:
  player_score:
    segment1:
      flashing: off
      color: 00acf0
      text: "{players[0].score:d}"

sound_player:
  mode_attract_started:
    rad_racer:
      track: music
      action: play
      loops: -1
  mode_attract_stopped:
    rad_racer:
      track: music
      action: stop
