#config_version=6

# segment_display_player:
#   player_score{game.num_players > 0}:
#     segment1:
#       text: "{players[0].score:d}"
#   player_score{game.num_players > 1}:
#     segment2:
#       text: "{players[1].score:d}"
#   player_score{game.num_players > 2}:
#     segment3:
#       text: "{players[2].score:d}"
#   player_score{game.num_players > 3}:
#     segment4:
#       text: "{players[3].score:d}"

sound_player:
  mode_attract_started:
    rad_racer:
      track: music
      action: play
      loops: -1
  mode_green_flag_stopped:
    particular:
      action: stop
  mode_attract_stopped:
    rad_racer:
      track: music
      action: stop
