#config_version=6

lights:
  l_backfire:
    subtype: led
    number: 1-0-0
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_01:
    type: grb
    subtype: led
    number: 1-0-1
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_02:
    type: grb
    subtype: led
    number: 1-0-2
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_03:
    type: grb
    subtype: led
    number: 1-0-3
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_04:
    type: grb
    subtype: led
    number: 1-0-4
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_05:
    type: grb
    subtype: led
    number: 1-0-5
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_06:
    type: grb
    subtype: led
    number: 1-0-6
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_07:
    type: grb
    subtype: led
    number: 1-0-7
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_08:
    type: grb
    subtype: led
    number: 1-0-8
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_09:
    type: grb
    subtype: led
    number: 1-0-9
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grooveline_10:
    type: grb
    subtype: led
    number: 1-0-10
    tags:
    - tag_lights
    - tag_lights_grooveline
    - tag_rgb
  l_grand_hole:
    subtype: led
    number: 1-0-11
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_rgb
  l_pit_tires:
    type: grb
    subtype: led
    number: 1-0-12
    tags:
    - tag_lights
    - tag_lights_pit
    - tag_rgb
  l_pit_lube:
    type: grb
    subtype: led
    number: 1-0-13
    tags:
    - tag_lights
    - tag_lights_pit
    - tag_rgb
  l_pit_fuel:
    type: grb
    subtype: led
    number: 1-0-14
    tags:
    - tag_lights
    - tag_lights_pit
    - tag_rgb
  l_pit_arrow2:
    subtype: led
    number: 1-0-15
    tags:
    - tag_lights
    - tag_lights_pit_arrow
    - tag_rgb
  l_pit_arrow1:
    subtype: led
    number: 1-0-16
    tags:
    - tag_lights
    - tag_lights_pit_arrow
    - tag_rgb
  l_mode_arrow1:
    type: grb
    subtype: led
    number: 1-0-17
    tags:
    - tag_lights
    - tag_lights_mode
    - tag_rgb
  l_mode_arrow2:
    type: grb
    subtype: led
    number: 1-0-18
    tags:
    - tag_lights
    - tag_lights_mode
    - tag_rgb
  l_prix_hole:
    subtype: led
    number: 1-0-19
    tags:
    - tag_lights
    - tag_lights_grand
    - tag_rgb
  l_shoot_fuel:
    subtype: led
    number: 1-0-20
    tags:
    - tag_lights
    - tag_lights_pit
    - tag_rgb
  l_loop_18:
    type: grb
    subtype: led
    number: 1-0-21
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_17:
    type: grb
    subtype: led
    number: 1-0-22
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_16:
    type: grb
    subtype: led
    number: 1-0-23
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_15:
    type: grb
    subtype: led
    number: 1-0-24
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_14:
    type: grb
    subtype: led
    number: 1-0-25
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_13:
    type: grb
    subtype: led
    number: 1-0-26
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_12:
    type: grb
    subtype: led
    number: 1-0-27
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_11:
    type: grb
    subtype: led
    number: 1-0-28
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_10:
    type: grb
    subtype: led
    number: 1-0-29
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_09:
    type: grb
    subtype: led
    number: 1-0-30
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_08:
    type: grb
    subtype: led
    number: 1-0-31
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_07:
    type: grb
    subtype: led
    number: 1-0-32
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_06:
    type: grb
    subtype: led
    number: 1-0-33
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_05:
    type: grb
    subtype: led
    number: 1-0-34
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_04:
    type: grb
    subtype: led
    number: 1-0-35
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_03:
    type: grb
    subtype: led
    number: 1-0-36
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_02:
    type: grb
    subtype: led
    number: 1-0-37
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_loop_01:
    type: grb
    subtype: led
    number: 1-0-38
    tags:
    - tag_lights
    - tag_lights_loop
    - tag_rgb
  l_mode_backbox:
    subtype: led
    number: 1-0-39
    tags:
    - tag_lights
    - tag_lights_mode
    - tag_rgb
  l_backbox_player_up4:
    type: grb
    subtype: led
    number: 1-0-40
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_player_up3:
    type: grb
    subtype: led
    number: 1-0-41
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_player_up2:
    type: grb
    subtype: led
    number: 1-0-42
    tags:
    - tag_lights
    - tag_lights_player_up
  l_backbox_player_up1:
    type: grb
    subtype: led
    number: 1-0-43
    tags:
    - tag_lights
    - tag_lights_player_up
