#config_version=6

lights:
  l_backfire:
    subtype: led
    number: 1-0-0
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_01:
    subtype: led
    number: 1-0-1
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_02:
    subtype: led
    number: 1-0-2
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_03:
    subtype: led
    number: 1-0-3
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_04:
    subtype: led
    number: 1-0-4
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_05:
    subtype: led
    number: 1-0-5
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_06:
    subtype: led
    number: 1-0-6
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_07:
    subtype: led
    number: 1-0-7
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_08:
    subtype: led
    number: 1-0-8
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_09:
    subtype: led
    number: 1-0-9
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grooveline_10:
    subtype: led
    number: 1-0-10
    tags:
    - tag_lights
    - tag_lights_grooveline
  l_grand_hole:
    subtype: led
    number: 1-0-11
    tags:
    - tag_lights
    - tag_lights_grand
  l_pit_tires:
    subtype: led
    number: 1-0-12
    tags:
    - tag_lights
    - tag_lights_pit
  l_pit_lube:
    subtype: led
    number: 1-0-13
    tags:
    - tag_lights
    - tag_lights_pit
  l_pit_fuel:
    subtype: led
    number: 1-0-14
    tags:
    - tag_lights
    - tag_lights_pit
  l_mode_arrow2:
    subtype: led
    number: 1-0-15
    tags:
    - tag_lights
    - tag_lights_mode
  l_mode_arrow1:
    subtype: led
    number: 1-0-16
    tags:
    - tag_lights
    - tag_lights_mode
  l_pit_arrow1:
    subtype: matrix
    number: 1-0-17
    tags:
    - tag_lights
    - tag_lights_arrow
  l_pit_arrow2:
    subtype: matrix
    number: 1-0-18
    tags:
    - tag_lights
    - tag_lights_arrow
  l_prix_hole:
    subtype: led
    number: 1-0-19
    tags:
    - tag_lights
    - tag_lights_grand
  l_mode_backbox:
    subtype: led
    number: 1-0-20
    tags:
    - tag_lights
    - tag_lights_mode
