#config_version=6

sound_system:
  buffer: 2048
  channels: 2
  enabled: true
  frequency: 44100
  tracks:
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.9
    effects:
      type: standard
      simultaneous_sounds: 10
      volume: 0.8
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.5
    ambience:
      type: standard
      simultaneous_sounds: 3
      volume: 0.2
    chimebox:
      type: standard
      simultaneous_sounds: 10
      volume: 0.4
