#config_version=6

sound_player:
  s_launch_inactive:
    comm_noise_on:
      action: play
    comm_noise_loop:
      action: play
      delay: 1.5s
      loops: -1
  ball_ending:
    comm_noise_loop:
      action: stop
    comm_noise_off:
      delay: 1.5s
      action: play
    mistake:
      action: play
