#config_version=6

sound_player:
  ball_starting{current_player.number == 1}:
    name1:
      action: play
      # delay to allow for player add chime sequence
      # and across all for consistency/simplicity
      delay: 1s
  ball_starting{current_player.number == 2}:
    name2:
      action: play
      delay: 1s
  ball_starting{current_player.number == 3}:
    name3:
      action: play
      delay: 1s
  ball_starting{current_player.number == 4}:
    name4:
      action: play
      delay: 1s
  ball_starting:
    player_up:
      action: play
      delay: 1s
  s_shooter_lane_inactive{current_player.tilt_warnings < 2}:
    comm_noise_on:
      action: play
    comm_noise_loop:
      action: play
      delay: 1.5s
      loops: -1
  ball_ending:
    comm_noise_loop:
      action: stop
    comm_noise_off:
      delay: 1.5s
      action: play
    backfire_loop:
      action: stop
    million_dollars:
      action: stop
    favourite_game:
      action: stop
    308in:
      action: stop
    blinding_lights:
      action: stop
    pit_ambience:
      action: stop
  mode_backfire_stopped:
    backfire_loop:
      action: stop
  mode_luxury_stopped:
    million_dollars:
      action: stop
  mode_grand_prix_stopped:
    favourite_game:
      action: stop
  mode_red_line_stopped:
    308in:
      action: stop
