#config_version=6

sound_system:
  buffer: 2048
  channels: 2
  enabled: true
  frequency: 44100
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.5
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    effects:
      type: standard
      simultaneous_sounds: 3
      volume: 0.8
    ambience:
      type: standard
      simultaneous_sounds: 2 # comm noise and track background
      volume: 0.4
    chimebox:
      type: standard
      simultaneous_sounds: 3
      volume: 0.3
