#config_version=6

sound_system:
  buffer: 2048
  channels: 2
  enabled: true
  frequency: 44100
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.3
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.6
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.4

sounds:
  rad_racer:
    file: rad_racer.ogg
    track: music
  particular:
    file: no-particular-place-to-go.ogg
    track: music
