#config_version=6

switches:
  s_spinner:
    # seems like auto-fire switches follow normal numbering
    # 12 -> 24
    # 13 -> 25
    # 14 -> 26
    # 15 -> 27
    number: 0-0-24 # direct with chime
    tags:
    - playfield_active
  s_tilt:
    number: 0-1-8
    tags:
    - tilt_warning
  s_coindoor:
    number: 0-1-9
  s_service_forward:
    number: 0-1-10
  s_service_down:
    number: 0-1-11
  s_service_up:
    number: 0-1-12
  s_service_back:
    number: 0-1-13
  s_start:
    number: 0-1-14
    tags:
    - start
  s_launch:
    number: 0-2-24
  s_pop1:
    number: 0-1-0 # direct
    tags:
    - pops
  s_pop2:
    number: 0-1-1 # direct
    tags:
    - pops
  s_pit_tires:
    number: 0-2-25
    tags:
    - playfield_active
    - pit_resource
  s_pit_lube:
    number: 0-2-26
    tags:
    - playfield_active
    - pit_resource
  s_backfire_hole:
    number: 0-2-27
    tags:
    - tag_hole
  s_pit_fuel:
    number: 0-2-28
    tags:
    - playfield_active
    - pit_resource
  s_prix_hole:
    number: 0-2-29
    tags:
    - tag_hole
  s_bonus_target:
    number: 0-2-30
    tags:
    - playfield_active
    - tag_rev
  s_grooveline:
    number: 0-2-31
    tags:
    - playfield_active
  s_save_target:
    number: 0-3-16
    tags:
    - playfield_active
    - tag_rev
  s_grand_hole:
    number: 0-3-17
    tags:
    - tag_hole
  s_multiball_target:
    number: 0-3-18
    tags:
    - playfield_active
  s_disqualifier:
    number: 0-3-19
    tags:
    - playfield_active
  s_swerve1:
    number: 0-3-20
    tags:
    - playfield_active
    - tag_swerve
  s_swerve2:
    number: 0-3-21
    tags:
    - playfield_active
    - tag_swerve
  s_flipper2:
    number: 0-3-22 # direct
    tags:
    - left_flipper
  s_slingshot2:
    number: 0-3-23 # direct
  s_inlane1:
    number: 0-3-24
    tags:
    - playfield_active
  s_outlane1:
    number: 0-3-25
    tags:
    - playfield_active
  s_inlane2:
    number: 0-3-26
    tags:
    - playfield_active
  s_outlane2:
    number: 0-3-27
    tags:
    - playfield_active
  s_shooter_lane:
    number: 0-3-28
  s_flipper1:
    number: 0-3-29 # direct
    tags:
    - right_flipper
  s_slingshot1:
    number: 0-3-30 # direct
  s_trough1:
    number: 0-3-31
    type: NC
  s_trough2:
    number: 0-4-24
    type: NC
  s_trough3:
    number: 0-4-25
    type: NC
  s_trough_jam:
    number: 0-4-27
    type: NC
  s_activate_playfield:
    number: 0-4-28
    tags:
    - playfield_active
