#config_version=6

switches:

  # Board 0 (inside cabinet) - only incandescent and coils

  # Board 1 (back of playfield)

  s_grooveline:
    number: 0-1-24
    tags:
    - playfield_active
    - tag_bell
  s_start:
    number: 0-1-25
    tags:
    - start
  # N/C 0-2-25
  s_grand_hole:
    number: 0-1-26
    tags:
    - tag_hole
    - tag_bell
  s_multiball_target:
    number: 0-1-27
    tags:
    - playfield_active
    - tag_bell
  s_disqualifier:
    number: 0-1-28
    tags:
    - playfield_active

  # Board 2 middle of playfield

  s_inlane2:
    number: 0-2-16
    tags:
    - playfield_active
    - tag_bell
  s_outlane2:
    number: 0-2-17
    tags:
    - playfield_active
    - tag_bell
  # N/C 0-2-18 -> 0-2-25
  s_flipper2:
    number: 0-3-24
    tags:
    - right_flipper
  s_slingshot2:
    number: 0-2-1 # direct
    tags:
    - tag_bell
  s_flipper1:
    number: 0-2-24
    tags:
    - left_flipper
  s_inlane1:
    number: 0-2-26
    tags:
    - playfield_active
    - tag_bell
  s_outlane1:
    number: 0-2-27
    tags:
    - playfield_active
    - tag_bell
  s_shooter_lane:
    number: 0-2-28

  # Board 3 (near grand hole)

  s_slingshot1:
    number: 0-3-1 # direct
    tags:
    - tag_bell
  s_trough_jam:
    number: 0-3-25
    type: NC
  s_trough1:
    number: 0-3-26
    type: NC
  s_trough2:
    number: 0-3-27
    type: NC
  s_trough3:
    number: 0-3-28
    type: NC
  s_save_target:
    number: 0-3-29
    tags:
    - playfield_active
    - tag_rev
    - tag_bell

  # Cobrapin Satellite (only board in chain 1)

  s_pop1:
    number: 1-0-1
    tags:
    - pops
    - tag_bell
  s_pop2:
    number: 1-0-2
    tags:
    - pops
    - tag_bell
  s_spinner:
    number: 1-0-3
    debounce: quick
    tags:
    - spinner
    - tag_bell

  s_pit_tires:
    number: 1-0-16
    tags:
    - playfield_active
    - pit_resource
  s_pit_lube:
    number: 1-0-17
    tags:
    - playfield_active
    - pit_resource
  s_backfire_hole:
    number: 1-0-18
    tags:
    - tag_hole
    - tag_bell
  s_bonus_target:
    number: 1-0-19
    tags:
    - playfield_active
    - tag_rev
    - tag_bell
  s_prix_hole:
    number: 1-0-20
    tags:
    - tag_hole
    - tag_bell
  s_pit_fuel:
    number: 1-0-21
    tags:
    - playfield_active
    - pit_resource
  s_swerve1:
    number: 1-0-22
    tags:
    - playfield_active
    - tag_swerve
    - tag_bell
  s_swerve2:
    number: 1-0-23
    tags:
    - playfield_active
    - tag_swerve
    - tag_bell


  # # TODO: Wire this bank:
  s_tilt:
    number: 1-0-24
    tags:
    - tilt_warning
  s_coindoor:
    number: 1-0-25
  s_service_forward:
    number: 1-0-26
  s_service_down:
    number: 1-0-27
  s_service_up:
    number: 1-0-28
  s_service_back:
    number: 1-0-29
  # unused:
  # 1-0-30,
  # 1-0-31
