#config_version=6

switches:
  s_spinner:
    number: 0-1-0 # direct with chime
    tags:
    - playfield_active
  s_tilt:
    number: 0-2-24
    tags:
    - tilt_warning
  s_coindoor:
    number: 0-2-25
  s_service_forward:
    number: 0-2-26
  s_service_down:
    number: 0-2-27
  s_service_up:
    number: 0-2-28
  s_service_back:
    number: 0-2-29
  s_start:
    number: 0-2-30
    tags:
    - start
  s_launch:
    number: 0-2-31
  s_pop1:
    number: 0-3-8 # direct
    tags:
    - pops
  s_pop2:
    number: 0-3-9 # direct
    tags:
    - pops
  s_pit_tires:
    number: 0-3-24
    tags:
    - playfield_active
    - pit_resource
  s_pit_lube:
    number: 0-3-25
    tags:
    - playfield_active
    - pit_resource
  s_backfire_hole:
    number: 0-3-26
    tags:
    - tag_hole
  s_pit_fuel:
    number: 0-3-27
    tags:
    - playfield_active
    - pit_resource
  s_prix_hole:
    number: 0-3-28
    tags:
    - tag_hole
  s_bonus_target:
    number: 0-3-29
    tags:
    - playfield_active
    - tag_rev
  s_grooveline:
    number: 0-4-24
    tags:
    - playfield_active
  s_save_target:
    number: 0-4-25
    tags:
    - playfield_active
    - tag_rev
  s_grand_hole:
    number: 0-4-26
    tags:
    - tag_hole
  s_multiball_target:
    number: 0-4-27
    tags:
    - playfield_active
  s_disqualifier:
    number: 0-4-28
    tags:
    - playfield_active
  s_swerve1:
    number: 0-4-29
    tags:
    - playfield_active
    - tag_swerve
  s_swerve2:
    number: 0-4-30
    tags:
    - playfield_active
    - tag_swerve
  s_flipper2:
    number: 0-5-0 # direct
    tags:
    - left_flipper
  s_slingshot2:
    number: 0-5-1 # direct
  s_inlane1:
    number: 0-5-16
    tags:
    - playfield_active
  s_outlane1:
    number: 0-5-17
    tags:
    - playfield_active
  s_inlane2:
    number: 0-5-24
    tags:
    - playfield_active
  s_outlane2:
    number: 0-5-25
    tags:
    - playfield_active
  s_shooter_lane:
    number: 0-5-26
  s_flipper1:
    number: 0-6-0 # direct
    tags:
    - right_flipper
  s_slingshot1:
    number: 0-6-1 # direct
  s_trough1:
    number: 0-6-24
    type: NC
  s_trough2:
    number: 0-6-25
    type: NC
  s_trough3:
    number: 0-6-26
    type: NC
  s_trough4:
    number: 0-6-27
    type: NC
  s_trough_jam:
    number: 0-6-31
    type: NC
  s_activate_playfield:
    number: 0-6-30
    tags:
    - playfield_active
