#config_version=6

switches:
  # Each OPP board can have up to 4 wings
  # positioned counter-clockwise from top-right
  #    -- 000000 || 00 [(1) 0-15 <= 0-8  ][(0) 0-7  <= 0-0  ][IO]
  # USB          ||
  #    -- 000000 || 0 [(2) 0-16 => 0-23 ][(3) 0-24 => 0-31 ]00000

  ############################
  # Board 0 - CAB1 (BACKBOX) #
  # inc, inc, inc, sol       #
  #                          #
  # sol 0-0 -> knocker       #
  ############################

  # NOTE: Only inserts and CPU-controlled coils here

  #############################
  # Board 1 - CAB2 (CHIMEBOX) #
  # sol, inp, inp, inp        #
  #                           #
  # sol 1-0 -> chime1         #
  # sol 1-1 -> chime2         #
  # sol 1-2 -> chime3         #
  # sol 1-3 -> shaker         #
  #############################

  s_spinner:
    number: 0-1-0 # direct with chime
    tags:
    - playfield_active

  ######################
  # Board 2 - MIXED    #
  # inc, inc, inc, inp #
  ######################
  s_tilt:
    number: 0-2-24
    tags:
    - tilt_warning
  s_coindoor:
    number: 0-2-25
  s_service_forward:
    number: 0-2-26
  s_service_down:
    number: 0-2-27
  s_service_up:
    number: 0-2-28
  s_service_back:
    number: 0-2-29
  s_start:
    number: 0-2-30
    tags:
    - start
  s_launch:
    number: 0-2-31

  ############################
  # Board 3 - PLAYFIELD1     #
  # sol, sol, inc, inp       #
  #                          #
  # sol 3-0 -> backfire_hole #
  # sol 3-1 -> tires         #
  # sol 3-2 -> oil           #
  # ------------------------ #
  # sol 3-8 -> pop1          #
  # sol 3-9 -> pop2          #
  # sol 3-10 -> fuel         #
  # sol 3-11 -> prix_hole    #
  ############################
  s_pop1:
    number: 0-3-8 # direct
    tags:
    - pops
  s_pop2:
    number: 0-3-9 # direct
    tags:
    - pops
  # north_drop left
  s_tires:
    number: 0-3-24
    tags:
    - playfield_active
    - pit_resource
  # north drop right
  s_oil:
    number: 0-3-25
    tags:
    - playfield_active
    - pit_resource
  s_backfire_hole:
    number: 0-3-26
    tags:
    - tag_hole
  # central drop right
  s_fuel:
    number: 0-3-27
    tags:
    - playfield_active
    - pit_resource
  s_prix_hole:
    number: 0-3-28
    tags:
    - tag_hole
  s_bonus_target:
    number: 0-3-29
    tags:
    - playfield_active
    - tag_rev

  # 3-30 OPEN
  # 3-31 OPEN

  ###########################
  # Board 4 - PLAYFIELD2    #
  # sol, inc, inc, inp      #
  #                         #
  # sol 4-0 -> disqualifier #
  # sol 4-1 -> grand_hole   #
  ###########################
  # north west rollover
  s_grooveline:
    number: 0-4-24
    tags:
    - playfield_active
  s_save_target:
    number: 0-4-25
    tags:
    - playfield_active
    - tag_rev
  s_grand_hole:
    number: 0-4-26
    tags:
    - tag_hole
  s_multiball_target:
    number: 0-4-27
    tags:
    - playfield_active
  # central drop left
  s_disqualifier:
    number: 0-4-28
    tags:
    - playfield_active
  s_swerve1:
    number: 0-4-29
    tags:
    - playfield_active
    - tag_swerve
  # UNUSED 4-30
  s_swerve2:
    number: 0-4-30
    tags:
    - playfield_active
    - tag_swerve

  ######################
  # Board 5 - APRON1   #
  # sol, inc, inc, inp #
  ######################
  s_flipper2:
    number: 0-5-0 # direct
    tags:
    - left_flipper
  s_slingshot2:
    number: 0-5-1 # direct
  # incands in this gap...
  s_inlane1:
    number: 0-5-16
    tags:
    - playfield_active
  s_outlane1:
    number: 0-5-17
    tags:
    - playfield_active
  # UNUSED 5-18
  # UNUSED 5-19
  # UNUSED 5-20
  # nUNUSED 5-21
  # UNUSED 5-22
  # UNUSED 5-23
  s_inlane2:
    number: 0-5-24
    tags:
    - playfield_active
  s_outlane2:
    number: 0-5-25
    tags:
    - playfield_active
  s_shooter_lane:
    number: 0-5-26
  # UNUSED 5-27
  # UNUSED 5-28
  # UNUSED 5-29
  # UNUSED 5-30
  # UNUSED 5-31

  ######################
  # Board 6 - APRON2   #
  # sol, inc, inp, inp #
  ######################
  s_flipper1:
    number: 0-6-0 # direct
    tags:
    - right_flipper
  s_slingshot1:
    number: 0-6-1 # direct
  s_trough1:
    number: 0-6-24
    type: NC
  s_trough2:
    number: 0-6-25
    type: NC
  s_trough3:
    number: 0-6-26
    type: NC
  s_trough4:
    number: 0-6-27
    type: NC
  # Room for more balls later...
  # UNUSED 6-28
  # UNUSED 6-29
  # UNUSED 6-30
  s_trough_jam:
    number: 0-6-31
    type: NC
  # NOTE: this is a dummy switch for use in testing
  #       without side effects
  s_activate_playfield:
    number: 0-6-30
    tags:
    - playfield_active
