#config_version=6

switches:
  # Each OPP board can have up to 4 wings
  # positioned counter-clockwise from top-right
  #    -- 000000 || 00 [(1) 0-15 <= 0-8  ][(0) 0-7  <= 0-0  ][IO]
  # USB          ||
  #    -- 000000 || 0 [(2) 0-16 => 0-23 ][(3) 0-24 => 0-31 ]00000

  #################
  # Board BACKBOX #
  #################

  # NOTE: Only inserts and CPU-controlled coils here

  ####################
  # Board PLAYFIELD1 #
  ####################
  # NOTE: dropping left spinner entirely

  s_pop1:
    number: 1-24
  s_pop2:
    number: 1-25
  # north_drop left
  s_qualifier3:
    number: 1-26
  s_qualifier2:
    number: 1-27
  s_podium_hole:
    number: 1-28
  s_disqualifier:
    number: 1-29
  s_prix_hole:
    number: 1-30
  # UNUSED 1-31

  #############
  # Board CAB #
  #############
  s_tilt:
    number: 2-24
  s_coindoor:
    number: 2-25
  s_service_forward:
    number: 2-26
  s_service_down:
    number: 2-27
  s_service_up:
    number: 2-28
  s_service_back:
    number: 2-29
  s_start:
    number: 2-30
  # UNUSED 2-31

  ####################
  # Board PLAYFIELD2 #
  ####################
  # north west rollover
  s_grooveline:
    number: 3-24
  s_grand_advance:
    number: 3-25
  s_grand_hole:
    number: 3-26
  # central drop left
  s_qualifier1:
    number: 3-27
  s_spinner:
    number: 3-28
  s_podium_advance2:
    number: 3-29
  s_prix_advance:
    number: 3-30
  s_podium_advance1:
    number: 3-31

  ################
  # Board APRON1 #
  ################
  s_flipper1_eos:
    number: 4-16
  s_slingshot1:
    number: 4-17
  s_inlane1:
    number: 4-18
  s_outlane1:
    number: 4-19
  s_flipper1:
    number: 4-20
  # UNUSED 4-21
  # UNUSED 4-22
  # UNUSED 4-23
  s_trough1:
    number: 4-24
  s_trough2:
    number: 4-25
  s_trough3:
    number: 4-26
  s_trough_jam:
    number: 4-27
  # UNUSED 4-28
  # UNUSED 4-29
  # UNUSED 4-30
  # UNUSED 4-31

  ################
  # Board APRON2 #
  ################
  s_flipper2_eos:
    number: 5-24
  s_slingshot2:
    number: 5-25
  s_inlane2:
    number: 5-26
  s_outlane2:
    number: 5-27
  s_shooter_lane:
    number: 5-28
  s_flipper2:
    number: 5-29
  # UNUSED 5-30
  # UNUSED 5-31
