#config_version=6

player_vars:
  is_multiball_ready:
    initial_value: 0
  is_grand_prix_multiball_ready:
    initial_value: 0
  lap_count:
    initial_value: 0
  spin_counter_count:
    initial_value: 0
  backfire_counter_count:
    initial_value: 0

  # # TODO: per ball bonuses
  # bonus_main:
  #   initial_value: 0
  # bonus_laps:
  #   initial_value: 0
  # bonus_game_progress:
  #   initial_value: 0

  # 2 is full
  # 1 is partial
  # 0 is empty
  level_fuel:
    # player begins game with partially empty tank
    initial_value: 1
  level_lube:
    initial_value: 2
  level_tires:
    initial_value: 2
  multiplier:
    initial_value: 1
  ##########################
  ## Wizard Mode Progress ##
  ##########################
  is_luxury_completed:
    initial_value: 0
  is_grooveline_completed:
    initial_value: 0
  is_grand_prix_completed:
    initial_value: 0
  # ^ the above three enable red_line
  #   per red_line_counter
  is_red_line_completed:
    initial_value: 0
