#config_version=6

player_vars:
  # 2 is full
  # 1 is partial
  # 0 is empty
  level_fuel:
    # player begins game with partially empty tank
    initial_value: 1
  level_oil:
    initial_value: 2
  level_tires:
    initial_value: 2
  is_grooveline:
    initial_value: 0
  is_grand_prix:
    initial_value: 0
