#config_version=6

player_vars:
  lap_count:
    initial_value: 0
  # 2 is full
  # 1 is partial
  # 0 is empty
  level_fuel:
    # player begins game with partially empty tank
    initial_value: 1
  level_oil:
    initial_value: 2
  level_tires:
    initial_value: 2
  ##########################
  ## Wizard Mode Progress ##
  ##########################
  is_luxury_completed:
    initial_value: 0
  is_grooveline_completed:
    initial_value: 0
  is_grand_prix_completed:
    initial_value: 0
  # ^ the above three enable red_line
  #   per red_line_counter
  is_red_line_completed:
    initial_value: 0
