#config_version=6

multiballs:
  luxury:
    ball_count: 2
    ball_count_type: total
    shoot_again: 10s
    enable_events:
    - mode_luxury_starting
    start_events:
    - mode_luxury_started
    stop_events:
    - mode_luxury_stopping
    tags:
    - multiball
