#config_version=6

tilt:
  warnings_to_tilt: 3
  multiple_hit_window: 500ms
  settle_time: 5s

slides:
  _overwrite: true
  tilt_warning_1:
    widgets:
    - type: text
      font_size: 140
      text: "Danger"
      color: orange
      anchor_y: middle
      anchor_x: center
    expire: 0.75s
  tilt_warning_2:
    widgets:
    - type: text
      font_size: 100
      text: "Danger, Danger"
      color: orange
      anchor_y: middle
      anchor_x: center
      animations:
        add_to_slide: pulsate_fast
    expire: 1.5s
  tilt:
    widgets:
    - type: text
      text: "TILT"
      font_size: 180
      color: red
      anchor_y: middle
      anchor_x: center
      animations:
        add_to_slide: pulsate_slow

show_player:
  tilt_warning_1:
    lights_blink:
      speed: 8
      priority: 1
      loops: 3
      show_tokens:
        lights: l_backbox_tilt
  tilt_warning_2:
    lights_blink:
      speed: 12
      priority: 2
      loops: 6
      show_tokens:
        lights: l_backbox_tilt
  tilt:
    lights_blink:
      action: stop
      priority: 3
      show_tokens:
        lights: l_backbox_tilt

sound_player:
  tilt_warning_1:
    tilt1:
      action: play
  tilt_warning_2:
    tilt2:
      action: play
  tilt:
    tilt3:
      action: play
