#config_version=6

mode:
  start_events:
  - logicblock_seq_backfire_qualifier_complete
  stop_events:
  - timer_backfire_timer_stopped
  restart_on_next_ball: false
  # kind of a purgatory mode between pit and green flag
  priority: 150
