#config_version=6

sound_player:
  mode_backfire_started:
    everybody:
      action: play
      loops: -1
  mode_backfire_stopping:
    everybody:
      action: stop
  sw_pops:
    backfire:
      block: true
