#config_version=6

variable_player:
  logicblock_backfire_counter_updated:
    backfire_counter_count:
      action: set
      int: value
  mode_green_flag_stopped:
    backfire_counter_count:
      action: set
      int: 0
  # Scoring
  sw_pops:
    score:
      int: ((1000 * current_player.backfire_counter_count) * current_player.multiplier)
      block: true
