# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Grand Prix '86 Pinball

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get install \
          build-essential git \
          python3-pip python3-venv \
          zlib1g-dev libjpeg-dev libtiff5-dev libtiff5-dev \
          libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev \
          libsdl2-mixer-dev gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly libgstreamer1.0-dev \
          libxine2-ffmpeg libsmpeg-dev libswscale-dev \
          libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev \
          libx11-dev libmtdev-dev build-essential libgl1-mesa-dev \
          libgles2-mesa-dev pulseaudio lsb-release \
          libgl1-mesa-dri libavfilter-dev libavdevice-dev libunwind-dev -y
    - name: Install app dependencies
      run: |
        pip install --upgrade \
          pip setuptools wheel build coveralls pillow
        pip install --upgrade Cython==0.29.36

        # Install MPF
        pip install mpf==0.57
        pip install mpf-mc==0.57
    - name: Test
      run: |
        bin/test
